In [23]:
import scraping
import pickle
import create_rawdf
%load_ext autoreload

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [26]:
autoreload

#データを取得

#開催日を取得

In [28]:
kaisai_date_list = scraping.scrape_kaisai_date(from_="2026-01", to_="2026-01")

  0%|          | 0/1 [00:00<?, ?it/s]

In [29]:
kaisai_date_list

['20260104',
 '20260105',
 '20260110',
 '20260111',
 '20260112',
 '20260117',
 '20260118',
 '20260124',
 '20260125']

In [30]:
race_id_list=scraping.scrape_race_id_list(kaisai_date_list)

[INFO] existing race_id: 10365

  0%|          | 0/9 [00:00<?, ?it/s]

In [24]:
with open("race_id_list.pickle","wb") as f:
    pickle.dump(race_id_list,f)

NameError: name 'race_id_list' is not defined

## raceの取得

In [6]:
with open("race_id_list.pickle","rb") as f:
    race_id_list=pickle.load(f)

In [7]:
html_paths_race=scraping.scrape_html_race(race_id_list=race_id_list)

  0%|          | 0/10365 [00:00<?, ?it/s]

skipped:202306010101
skipped:202306010102
skipped:202306010103
skipped:202306010104
skipped:202306010105
skipped:202306010106
skipped:202306010107
skipped:202306010108
skipped:202306010109
skipped:202306010110
skipped:202306010111
skipped:202306010112
skipped:202307010101
skipped:202307010102
skipped:202307010103
skipped:202307010104
skipped:202307010105
skipped:202307010106
skipped:202307010107
skipped:202307010108
skipped:202307010109
skipped:202307010110
skipped:202307010111
skipped:202307010112
skipped:202306010201
skipped:202306010202
skipped:202306010203
skipped:202306010204
skipped:202306010205
skipped:202306010206
skipped:202306010207
skipped:202306010208
skipped:202306010209
skipped:202306010210
skipped:202306010211
skipped:202306010212
skipped:202307010201
skipped:202307010202
skipped:202307010203
skipped:202307010204
skipped:202307010205
skipped:202307010206
skipped:202307010207
skipped:202307010208
skipped:202307010209
skipped:202307010210
skipped:202307010211
skipped:202307010212
skipped:202306010301
skipped:202306010302
skipped:202306010303
skipped:202306010304
skipped:202306010305
skipped:202306010306
skipped:202306010307
skipped:202306010308
skipped:202306010309
skipped:202306010310
skipped:202306010311
skipped:202306010312
skipped:202307010301
skipped:202307010302
skipped:202307010303
skipped:202307010304
skipped:202307010305
skipped:202307010306
skipped:202307010307
skipped:202307010308
skipped:202307010309
skipped:202307010310
skipped:202307010311
skipped:202307010312
skipped:202306010401
skipped:202306010402
skipped:202306010403
skipped:202306010404
skipped:202306010405
skipped:202306010406
skipped:202306010407
skipped:202306010408
skipped:202306010409
skipped:202306010410
skipped:202306010411
skipped:202306010412
skipped:202307010401
skipped:202307010402
skipped:202307010403
skipped:202307010404
skipped:202307010405
skipped:202307010406
skipped:202307010407
skipped:202307010408
skipped:202307010409
skipped:202307010410
skipped:202307010411
skipped:202307010412
skipped:202306010501
skipped:202306010502
skipped:202306010503
skipped:202306010504
skipped:202306010505
skipped:202306010506
skipped:202306010507
skipped:202306010508
skipped:202306010509
skipped:202306010510
skipped:202306010511
skipped:202306010512
skipped:202307010501
skipped:202307010502
skipped:202307010503
skipped:202307010504
skipped:202307010505
skipped:202307010506
skipped:202307010507
skipped:202307010508
skipped:202307010509
skipped:202307010510
skipped:202307010511
skipped:202307010512
skipped:202310010101
skipped:202310010102
skipped:202310010103
skipped:202310010104
skipped:202310010105
skipped:202310010106
skipped:202310010107
skipped:202310010108
skipped:202310010109
skipped:202310010110
skipped:202310010111
skipped:202310010112
skipped:202306010601
skipped:202306010602
skipped:202306010603
skipped:202306010604
skipped:202306010605
skipped:202306010606
skipped:202306010607
skipped:202306010608
skipped:202306010609
skipped:202306010610
skipped:202306010611
skipped:202306010612
skipped:202307010601
skipped:202307010602
skipped:202307010603
skipped:202307010604
skipped:202307010605
skipped:202307010606
skipped:202307010607
skipped:202307010608
skipped:202307010609
skipped:202307010610
skipped:202307010611
skipped:202307010612
skipped:202310010201
skipped:202310010202
skipped:202310010203
skipped:202310010204
skipped:202310010205
skipped:202310010206
skipped:202310010207
skipped:202310010208
skipped:202310010209
skipped:202310010210
skipped:202310010211
skipped:202310010212
skipped:202306010701
skipped:202306010702
skipped:202306010703
skipped:202306010704
skipped:202306010705
skipped:202306010706
skipped:202306010707
skipped:202306010708
skipped:202306010709
skipped:202306010710
skipped:202306010711
skipped:202306010712
skipped:202307010701
skipped:202307010702
skipped:202307010703
skipped:202307010704
skipped:202307010705
skipped:202307010706
skipped:202307010707
skipped:202307010708
skipped:202307010709
skipped:202307010710
skipped:202307010711
skipped:202307010712
skipped:202310010301
skipped:202310010302
skipped:202310010303
skipped:202310010304
skipped:202310010305
skipped:202310010306
skipped:202310010307
skipped:202310010308
skipped:202310010309
skipped:202310010310
skipped:202310010311
skipped:202310010312
skipped:202306010801
skipped:202306010802
skipped:202306010803
skipped:202306010804
skipped:202306010805
skipped:202306010806
skipped:202306010807
skipped:202306010808
skipped:202306010809
skipped:202306010810
skipped:202306010811
skipped:202306010812
skipped:202307010801
skipped:202307010802
skipped:202307010803
skipped:202307010804
skipped:202307010805
skipped:202307010806
skipped:202307010807
skipped:202307010808
skipped:202307010809
skipped:202307010810
skipped:202307010811
skipped:202307010812
skipped:202310010401
skipped:202310010402
skipped:202310010403
skipped:202310010404
skipped:202310010405
skipped:202310010406
skipped:202310010407
skipped:202310010408
skipped:202310010409
skipped:202310010410
skipped:202310010411
skipped:202310010412
skipped:202305010101
skipped:202305010102
skipped:202305010103
skipped:202305010104
skipped:202305010105
skipped:202305010106
skipped:202305010107
skipped:202305010108
skipped:202305010109
skipped:202305010110
skipped:202305010111
skipped:202305010112
skipped:202307010901
skipped:202307010902
skipped:202307010903
skipped:202307010904
skipped:202307010905
skipped:202307010906
skipped:202307010907
skipped:202307010908
skipped:202307010909
skipped:202307010910
skipped:202307010911
skipped:202307010912
skipped:202310010501
skipped:202310010502
skipped:202310010503
skipped:202310010504
skipped:202310010505
skipped:202310010506
skipped:202310010507
skipped:202310010508
skipped:202310010509
skipped:202310010510
skipped:202310010511
skipped:202310010512
skipped:202305010201
skipped:202305010202
skipped:202305010203
skipped:202305010204
skipped:202305010205
skipped:202305010206
skipped:202305010207
skipped:202305010208
skipped:202305010209
skipped:202305010210
skipped:202305010211
skipped:202305010212
skipped:202307011001
skipped:202307011002
skipped:202307011003
skipped:202307011004
skipped:202307011005
skipped:202307011006
skipped:202307011007
skipped:202307011008
skipped:202307011009
skipped:202307011010
skipped:202307011011
skipped:202307011012
skipped:202310010601
skipped:202310010602
skipped:202310010603
skipped:202310010604
skipped:202310010605
skipped:202310010606
skipped:202310010607
skipped:202310010608
skipped:202310010609
skipped:202310010610
skipped:202310010611
skipped:202310010612
skipped:202305010301
skipped:202305010302
skipped:202305010303
skipped:202305010304
skipped:202305010305
skipped:202305010306
skipped:202305010307
skipped:202305010308
skipped:202305010309
skipped:202305010310
skipped:202305010311
skipped:202305010312
skipped:202307011101
skipped:202307011102
skipped:202307011103
skipped:202307011104
skipped:202307011105
skipped:202307011106
skipped:202307011107
skipped:202307011108
skipped:202307011109
skipped:202307011110
skipped:202307011111
skipped:202307011112
skipped:202310010701
skipped:202310010702
skipped:202310010703
skipped:202310010704
skipped:202310010705
skipped:202310010706
skipped:202310010707
skipped:202310010708
skipped:202310010709
skipped:202310010710
skipped:202310010711
skipped:202310010712
skipped:202305010401
skipped:202305010402
skipped:202305010403
skipped:202305010404
skipped:202305010405
skipped:202305010406
skipped:202305010407
skipped:202305010408
skipped:202305010409
skipped:202305010410
skipped:202305010411
skipped:202305010412
skipped:202307011201
skipped:202307011202
skipped:202307011203
skipped:202307011204
skipped:202307011205
skipped:202307011206
skipped:202307011207
skipped:202307011208
skipped:202307011209
skipped:202307011210
skipped:202307011211
skipped:202307011212
skipped:202310010801
skipped:202310010802
skipped:202310010803
skipped:202310010804
skipped:202310010805
skipped:202310010806
skipped:202310010807
skipped:202310010808
skipped:202310010809
skipped:202310010810
skipped:202310010811
skipped:202310010812
skipped:202305010501
skipped:202305010502
skipped:202305010503
skipped:202305010504
skipped:202305010505
skipped:202305010506
skipped:202305010507
skipped:202305010508
skipped:202305010509
skipped:202305010510
skipped:202305010511
skipped:202305010512
skipped:202309010101
skipped:202309010102
skipped:202309010103
skipped:202309010104
skipped:202309010105
skipped:202309010106
skipped:202309010107
skipped:202309010108
skipped:202309010109
skipped:202309010110
skipped:202309010111
skipped:202309010112
skipped:202310020101
skipped:202310020102
skipped:202310020103
skipped:202310020104
skipped:202310020105
skipped:202310020106
skipped:202310020107
skipped:202310020108
skipped:202310020109
skipped:202310020110
skipped:202310020111
skipped:202310020112
skipped:202305010601
skipped:202305010602
skipped:202305010603
skipped:202305010604
skipped:202305010605
skipped:202305010606
skipped:202305010607
skipped:202305010608
skipped:202305010609
skipped:202305010610
skipped:202305010611
skipped:202305010612
skipped:202309010201
skipped:202309010202
skipped:202309010203
skipped:202309010204
skipped:202309010205
skipped:202309010206
skipped:202309010207
skipped:202309010208
skipped:202309010209
skipped:202309010210
skipped:202309010211
skipped:202309010212
skipped:202310020201
skipped:202310020202
skipped:202310020203
skipped:202310020204
skipped:202310020205
skipped:202310020206
skipped:202310020207
skipped:202310020208
skipped:202310020209
skipped:202310020210
skipped:202310020211
skipped:202310020212
skipped:202305010701
skipped:202305010702
skipped:202305010703
skipped:202305010704
skipped:202305010705
skipped:202305010706
skipped:202305010707
skipped:202305010708
skipped:202305010709
skipped:202305010710
skipped:202305010711
skipped:202305010712
skipped:202309010301
skipped:202309010302
skipped:202309010303
skipped:202309010304
skipped:202309010305
skipped:202309010306
skipped:202309010307
skipped:202309010308
skipped:202309010309
skipped:202309010310
skipped:202309010311
skipped:202309010312
skipped:202310020301
skipped:202310020302
skipped:202310020303
skipped:202310020304
skipped:202310020305
skipped:202310020306
skipped:202310020307
skipped:202310020308
skipped:202310020309
skipped:202310020310
skipped:202310020311
skipped:202310020312
skipped:202305010801
skipped:202305010802
skipped:202305010803
skipped:202305010804
skipped:202305010805
skipped:202305010806
skipped:202305010807
skipped:202305010808
skipped:202305010809
skipped:202305010810
skipped:202305010811
skipped:202305010812
skipped:202309010401
skipped:202309010402
skipped:202309010403
skipped:202309010404
skipped:202309010405
skipped:202309010406
skipped:202309010407
skipped:202309010408
skipped:202309010409
skipped:202309010410
skipped:202309010411
skipped:202309010412
skipped:202310020401
skipped:202310020402
skipped:202310020403
skipped:202310020404
skipped:202310020405
skipped:202310020406
skipped:202310020407
skipped:202310020408
skipped:202310020409
skipped:202310020410
skipped:202310020411
skipped:202310020412
skipped:202306020101
skipped:202306020102
skipped:202306020103
skipped:202306020104
skipped:202306020105
skipped:202306020106
skipped:202306020107
skipped:202306020108
skipped:202306020109
skipped:202306020110
skipped:202306020111
skipped:202306020112
skipped:202309010501
skipped:202309010502
skipped:202309010503
skipped:202309010504
skipped:202309010505
skipped:202309010506
skipped:202309010507
skipped:202309010508
skipped:202309010509
skipped:202309010510
skipped:202309010511
skipped:202309010512
skipped:202310020501
skipped:202310020502
skipped:202310020503
skipped:202310020504
skipped:202310020505
skipped:202310020506
skipped:202310020507
skipped:202310020508
skipped:202310020509
skipped:202310020510
skipped:202310020511
skipped:202310020512
skipped:202306020201
skipped:202306020202
skipped:202306020203
skipped:202306020204
skipped:202306020205
skipped:202306020206
skipped:202306020207
skipped:202306020208
skipped:202306020209
skipped:202306020210
skipped:202306020211
skipped:202306020212
skipped:202309010601
skipped:202309010602
skipped:202309010603
skipped:202309010604
skipped:202309010605
skipped:202309010606
skipped:202309010607
skipped:202309010608
skipped:202309010609
skipped:202309010610
skipped:202309010611
skipped:202309010612
skipped:202310020601
skipped:202310020602
skipped:202310020603
skipped:202310020604
skipped:202310020605
skipped:202310020606
skipped:202310020607
skipped:202310020608
skipped:202310020609
skipped:202310020610
skipped:202310020611
skipped:202310020612
skipped:202306020301
skipped:202306020302
skipped:202306020303
skipped:202306020304
skipped:202306020305
skipped:202306020306
skipped:202306020307
skipped:202306020308
skipped:202306020309
skipped:202306020310
skipped:202306020311
skipped:202306020312
skipped:202309010701
skipped:202309010702
skipped:202309010703
skipped:202309010704
skipped:202309010705
skipped:202309010706
skipped:202309010707
skipped:202309010708
skipped:202309010709
skipped:202309010710
skipped:202309010711
skipped:202309010712
skipped:202306020401
skipped:202306020402
skipped:202306020403
skipped:202306020404
skipped:202306020405
skipped:202306020406
skipped:202306020407
skipped:202306020408
skipped:202306020409
skipped:202306020410
skipped:202306020411
skipped:202306020412
skipped:202309010801
skipped:202309010802
skipped:202309010803
skipped:202309010804
skipped:202309010805
skipped:202309010806
skipped:202309010807
skipped:202309010808
skipped:202309010809
skipped:202309010810
skipped:202309010811
skipped:202309010812
skipped:202306020501
skipped:202306020502
skipped:202306020503
skipped:202306020504
skipped:202306020505
skipped:202306020506
skipped:202306020507
skipped:202306020508
skipped:202306020509
skipped:202306020510
skipped:202306020511
skipped:202306020512
skipped:202309010901
skipped:202309010902
skipped:202309010903
skipped:202309010904
skipped:202309010905
skipped:202309010906
skipped:202309010907
skipped:202309010908
skipped:202309010909
skipped:202309010910
skipped:202309010911
skipped:202309010912
skipped:202307020101
skipped:202307020102
skipped:202307020103
skipped:202307020104
skipped:202307020105
skipped:202307020106
skipped:202307020107
skipped:202307020108
skipped:202307020109
skipped:202307020110
skipped:202307020111
skipped:202307020112
skipped:202306020601
skipped:202306020602
skipped:202306020603
skipped:202306020604
skipped:202306020605
skipped:202306020606
skipped:202306020607
skipped:202306020608
skipped:202306020609
skipped:202306020610
skipped:202306020611
skipped:202306020612
skipped:202309011001
skipped:202309011002
skipped:202309011003
skipped:202309011004
skipped:202309011005
skipped:202309011006
skipped:202309011007
skipped:202309011008
skipped:202309011009
skipped:202309011010
skipped:202309011011
skipped:202309011012
skipped:202307020201
skipped:202307020202
skipped:202307020203
skipped:202307020204
skipped:202307020205
skipped:202307020206
skipped:202307020207
skipped:202307020208
skipped:202307020209
skipped:202307020210
skipped:202307020211
skipped:202307020212
skipped:202306020701
skipped:202306020702
skipped:202306020703
skipped:202306020704
skipped:202306020705
skipped:202306020706
skipped:202306020707
skipped:202306020708
skipped:202306020709
skipped:202306020710
skipped:202306020711
skipped:202306020712
skipped:202309011101
skipped:202309011102
skipped:202309011103
skipped:202309011104
skipped:202309011105
skipped:202309011106
skipped:202309011107
skipped:202309011108
skipped:202309011109
skipped:202309011110
skipped:202309011111
skipped:202309011112
skipped:202307020301
skipped:202307020302
skipped:202307020303
skipped:202307020304
skipped:202307020305
skipped:202307020306
skipped:202307020307
skipped:202307020308
skipped:202307020309
skipped:202307020310
skipped:202307020311
skipped:202307020312
skipped:202306020801
skipped:202306020802
skipped:202306020803
skipped:202306020804
skipped:202306020805
skipped:202306020806
skipped:202306020807
skipped:202306020808
skipped:202306020809
skipped:202306020810
skipped:202306020811
skipped:202306020812
skipped:202309011201
skipped:202309011202
skipped:202309011203
skipped:202309011204
skipped:202309011205
skipped:202309011206
skipped:202309011207
skipped:202309011208
skipped:202309011209
skipped:202309011210
skipped:202309011211
skipped:202309011212
skipped:202307020401
skipped:202307020402
skipped:202307020403
skipped:202307020404
skipped:202307020405
skipped:202307020406
skipped:202307020407
skipped:202307020408
skipped:202307020409
skipped:202307020410
skipped:202307020411
skipped:202307020412
skipped:202306030101
skipped:202306030102
skipped:202306030103
skipped:202306030104
skipped:202306030105
skipped:202306030106
skipped:202306030107
skipped:202306030108
skipped:202306030109
skipped:202306030110
skipped:202306030111
skipped:202306030112
skipped:202309020101
skipped:202309020102
skipped:202309020103
skipped:202309020104
skipped:202309020105
skipped:202309020106
skipped:202309020107
skipped:202309020108
skipped:202309020109
skipped:202309020110
skipped:202309020111
skipped:202309020112
skipped:202307020501
skipped:202307020502
skipped:202307020503
skipped:202307020504
skipped:202307020505
skipped:202307020506
skipped:202307020507
skipped:202307020508
skipped:202307020509
skipped:202307020510
skipped:202307020511
skipped:202307020512
skipped:202306030201
skipped:202306030202
skipped:202306030203
skipped:202306030204
skipped:202306030205
skipped:202306030206
skipped:202306030207
skipped:202306030208
skipped:202306030209
skipped:202306030210
skipped:202306030211
skipped:202306030212
skipped:202309020201
skipped:202309020202
skipped:202309020203
skipped:202309020204
skipped:202309020205
skipped:202309020206
skipped:202309020207
skipped:202309020208
skipped:202309020209
skipped:202309020210
skipped:202309020211
skipped:202309020212
skipped:202307020601
skipped:202307020602
skipped:202307020603
skipped:202307020604
skipped:202307020605
skipped:202307020606
skipped:202307020607
skipped:202307020608
skipped:202307020609
skipped:202307020610
skipped:202307020611
skipped:202307020612
skipped:202306030301
skipped:202306030302
skipped:202306030303
skipped:202306030304
skipped:202306030305
skipped:202306030306
skipped:202306030307
skipped:202306030308
skipped:202306030309
skipped:202306030310
skipped:202306030311
skipped:202306030312
skipped:202309020301
skipped:202309020302
skipped:202309020303
skipped:202309020304
skipped:202309020305
skipped:202309020306
skipped:202309020307
skipped:202309020308
skipped:202309020309
skipped:202309020310
skipped:202309020311
skipped:202309020312
skipped:202306030401
skipped:202306030402
skipped:202306030403
skipped:202306030404
skipped:202306030405
skipped:202306030406
skipped:202306030407
skipped:202306030408
skipped:202306030409
skipped:202306030410
skipped:202306030411
skipped:202306030412
skipped:202309020401
skipped:202309020402
skipped:202309020403
skipped:202309020404
skipped:202309020405
skipped:202309020406
skipped:202309020407
skipped:202309020408
skipped:202309020409
skipped:202309020410
skipped:202309020411
skipped:202309020412
skipped:202306030501
skipped:202306030502
skipped:202306030503
skipped:202306030504
skipped:202306030505
skipped:202306030506
skipped:202306030507
skipped:202306030508
skipped:202306030509
skipped:202306030510
skipped:202306030511
skipped:202306030512
skipped:202309020501
skipped:202309020502
skipped:202309020503
skipped:202309020504
skipped:202309020505
skipped:202309020506
skipped:202309020507
skipped:202309020508
skipped:202309020509
skipped:202309020510
skipped:202309020511
skipped:202309020512
skipped:202303010101
skipped:202303010102
skipped:202303010103
skipped:202303010104
skipped:202303010105
skipped:202303010106
skipped:202303010107
skipped:202303010108
skipped:202303010109
skipped:202303010110
skipped:202303010111
skipped:202303010112
skipped:202306030601
skipped:202306030602
skipped:202306030603
skipped:202306030604

In [5]:
#html_paths_raceが失われた場合はファイルから読み込む

if "html_paths_race" not in locals():
    html_paths_race=list(scraping.HTML_RACE_DIR.glob("*bin"))

In [6]:
html_paths_race

[PosixPath('../data/html/race/202406010111.bin'),
 PosixPath('../data/html/race/202503020112.bin'),
 PosixPath('../data/html/race/202509050506.bin'),
 PosixPath('../data/html/race/202309020109.bin'),
 PosixPath('../data/html/race/202303020408.bin'),
 PosixPath('../data/html/race/202307020402.bin'),
 PosixPath('../data/html/race/202410020205.bin'),
 PosixPath('../data/html/race/202308010304.bin'),
 PosixPath('../data/html/race/202304040412.bin'),
 PosixPath('../data/html/race/202305020202.bin'),
 PosixPath('../data/html/race/202309040111.bin'),
 PosixPath('../data/html/race/202302020503.bin'),
 PosixPath('../data/html/race/202510010602.bin'),
 PosixPath('../data/html/race/202408020609.bin'),
 PosixPath('../data/html/race/202304010102.bin'),
 PosixPath('../data/html/race/202309040909.bin'),
 PosixPath('../data/html/race/202410030212.bin'),
 PosixPath('../data/html/race/202308011106.bin'),
 PosixPath('../data/html/race/202306040108.bin'),
 PosixPath('../data/html/race/202310020412.bin'),
 PosixPath('../data/html/race/202508040302.bin'),
 PosixPath('../data/html/race/202506010604.bin'),
 PosixPath('../data/html/race/202506040402.bin'),
 PosixPath('../data/html/race/202307010403.bin'),
 PosixPath('../data/html/race/202310030709.bin'),
 PosixPath('../data/html/race/202401020105.bin'),
 PosixPath('../data/html/race/202501010309.bin'),
 PosixPath('../data/html/race/202509050306.bin'),
 PosixPath('../data/html/race/202304030506.bin'),
 PosixPath('../data/html/race/202506040101.bin'),
 PosixPath('../data/html/race/202505020607.bin'),
 PosixPath('../data/html/race/202408060209.bin'),
 PosixPath('../data/html/race/202504010205.bin'),
 PosixPath('../data/html/race/202307040307.bin'),
 PosixPath('../data/html/race/202310020410.bin'),
 PosixPath('../data/html/race/202408020111.bin'),
 PosixPath('../data/html/race/202308010106.bin'),
 PosixPath('../data/html/race/202304030607.bin'),
 PosixPath('../data/html/race/202501010205.bin'),
 PosixPath('../data/html/race/202507010801.bin'),
 PosixPath('../data/html/race/202302010105.bin'),
 PosixPath('../data/html/race/202508040703.bin'),
 PosixPath('../data/html/race/202509030305.bin'),
 PosixPath('../data/html/race/202306030601.bin'),
 PosixPath('../data/html/race/202306010712.bin'),
 PosixPath('../data/html/race/202304020206.bin'),
 PosixPath('../data/html/race/202507010710.bin'),
 PosixPath('../data/html/race/202304010612.bin'),
 PosixPath('../data/html/race/202408020501.bin'),
 PosixPath('../data/html/race/202405030308.bin'),
 PosixPath('../data/html/race/202409010705.bin'),
 PosixPath('../data/html/race/202505040210.bin'),
 PosixPath('../data/html/race/202406010209.bin'),
 PosixPath('../data/html/race/202505020706.bin'),
 PosixPath('../data/html/race/202506050405.bin'),
 PosixPath('../data/html/race/202509040702.bin'),
 PosixPath('../data/html/race/202401010509.bin'),
 PosixPath('../data/html/race/202507020112.bin'),
 PosixPath('../data/html/race/202309010407.bin'),
 PosixPath('../data/html/race/202407010601.bin'),
 PosixPath('../data/html/race/202408070909.bin'),
 PosixPath('../data/html/race/202503020709.bin'),
 PosixPath('../data/html/race/202506020603.bin'),
 PosixPath('../data/html/race/202308010612.bin'),
 PosixPath('../data/html/race/202410030411.bin'),
 PosixPath('../data/html/race/202303010303.bin'),
 PosixPath('../data/html/race/202504010403.bin'),
 PosixPath('../data/html/race/202404030303.bin'),
 PosixPath('../data/html/race/202309030310.bin'),
 PosixPath('../data/html/race/202404030406.bin'),
 PosixPath('../data/html/race/202309040901.bin'),
 PosixPath('../data/html/race/202408030704.bin'),
 PosixPath('../data/html/race/202304010305.bin'),
 PosixPath('../data/html/race/202405030602.bin'),
 PosixPath('../data/html/race/202410020403.bin'),
 PosixPath('../data/html/race/202506030107.bin'),
 PosixPath('../data/html/race/202310020510.bin'),
 PosixPath('../data/html/race/202306050412.bin'),
 PosixPath('../data/html/race/202402010203.bin'),
 PosixPath('../data/html/race/202407020403.bin'),
 PosixPath('../data/html/race/202407040610.bin'),
 PosixPath('../data/html/race/202310020301.bin'),
 PosixPath('../data/html/race/202408010210.bin'),
 PosixPath('../data/html/race/202509040809.bin'),
 PosixPath('../data/html/race/202508040310.bin'),
 PosixPath('../data/html/race/202409010802.bin'),
 PosixPath('../data/html/race/202408060307.bin'),
 PosixPath('../data/html/race/202508030304.bin'),
 PosixPath('../data/html/race/202307020412.bin'),
 PosixPath('../data/html/race/202304040208.bin'),
 PosixPath('../data/html/race/202308020411.bin'),
 PosixPath('../data/html/race/202307010304.bin'),
 PosixPath('../data/html/race/202302010212.bin'),
 PosixPath('../data/html/race/202302020504.bin'),
 PosixPath('../data/html/race/202507030708.bin'),
 PosixPath('../data/html/race/202501020210.bin'),
 PosixPath('../data/html/race/202509010610.bin'),
 PosixPath('../data/html/race/202306050508.bin'),
 PosixPath('../data/html/race/202306050203.bin'),
 PosixPath('../data/html/race/202404010512.bin'),
 PosixPath('../data/html/race/202309040804.bin'),
 PosixPath('../data/html/race/202509050501.bin'),
 PosixPath('../data/html/race/202307040511.bin'),
 PosixPath('../data/html/race/202404030803.bin'),
 PosixPath('../data/html/race/202508040305.bin'),
 PosixPath('../data/html/race/202303010210.bin'),
 PosixPath('../data/html/race/202508030108.bin'),
 PosixPath('../data/html/race/202507010508.bin'),
 PosixPath('../data/html/race/202306010808.bin'),
 PosixPath('../data/html/race/202509010405.bin'),
 PosixPath('../data/html/race/202303030404.bin'),
 PosixPath('../data/html/race/202504010802.bin'),
 PosixPath('../data/html/race/202309011008.bin'),
 PosixPath('../data/html/race/202409020506.bin'),
 PosixPath('../data/html/race/202506050304.bin'),
 PosixPath('../data/html/race/202406040406.bin'),
 PosixPath('../data/html/race/202505010508.bin'),
 PosixPath('../data/html/race/202301010212.bin'),
 PosixPath('../data/html/race/202306030508.bin'),
 PosixPath('../data/html/race/202504010304.bin'),
 PosixPath('../data/html/race/202309030507.bin'),
 PosixPath('../data/html/race/202507020109.bin'),
 PosixPath('../data/html/race/202306050707.bin'),
 PosixPath('../data/html/race/202507030606.bin'),
 PosixPath('../data/html/race/202405021006.bin'),
 PosixPath('../data/html/race/202404020205.bin'),
 PosixPath('../data/html/race/202408010708.bin'),
 PosixPath('../data/html/race/202308010404.bin'),
 PosixPath('../data/html/race/202509010111.bin'),
 PosixPath('../data/html/race/202408050402.bin'),
 PosixPath('../data/html/race/202505050406.bin'),
 PosixPath('../data/html/race/202510020403.bin'),
 PosixPath('../data/html/race/202405020602.bin'),
 PosixPath('../data/html/race/202506020804.bin'),
 PosixPath('../data/html/race/202405010211.bin'),
 PosixPath('../data/html/race/202306010309.bin'),
 PosixPath('../data/html/race/202508040201.bin'),
 PosixPath('../data/html/race/202304010406.bin'),
 PosixPath('../data/html/race/202503030306.bin'),
 PosixPath('../data/html/race/202407040110.bin'),
 PosixPath('../data/html/race/202406020703.bin'),
 PosixPath('../data/html/race/202505030402.bin'),
 PosixPath('../data/html/race/202408050211.bin'),
 PosixPath('../data/html/race/202505010808.bin'),
 PosixPath('../data/html/race/202308030401.bin'),
 PosixPath('../data/html/race/202405030404.bin'),
 PosixPath('../data/html/race/202407040304.bin'),
 PosixPath('../data/html/race/202504040109.bin'),
 PosixPath('../data/html/race/202308020705.bin'),
 PosixPath('../data/html/race/202508020105.bin'),
 PosixPath('../data/html/race/202407030910.bin'),
 PosixPath('../data/html/race/202408050604.bin'),
 PosixPath('../data/html/race/202501010805.bin'),
 PosixPath('../data/html/race/202309040706.bin'),
 PosixPath('../data/html/race/202306030405.bin'),
 PosixPath('../data/html/race/202505040710.bin'),
 PosixPath('../data/html/race/202504010608.bin'),
 PosixPath('../data/html/race/202506030711.bin'),
 PosixPath('../data/html/race/202501020608.bin'),
 PosixPath('../data/html/race/202406030509.bin'),
 PosixPath('../data/html/race/202508040204.bin'),
 PosixPath('../data/html/race/202507050408.bin'),
 PosixPath('../data/html/race/202304010501.bin'),
 PosixPath('../data/html/race/202509010202.bin'),
 PosixPath('../data/html/race/202507010303.bin'),
 PosixPath('../data/html/race/202308020607.bin'),
 PosixPath('../data/html/race/202405040601.bin'),
 PosixPath('../data/html/race/202308010807.bin'),
 PosixPath('../data/html/race/202402010206.bin'),
 PosixPath('../data/html/race/202410010308.bin'),
 PosixPath('../data/html/race/202309010701.bin'),
 PosixPath('../data/html/race/202310010501.bin'),
 PosixPath('../data/html/race/202408060509.bin'),
 PosixPath('../data/html/race/202404010401.bin'),
 PosixPath('../data/html/race/202509050605.bin'),
 PosixPath('../data/html/race/202406040112.bin'),
 PosixPath('../data/html/race/202306040707.bin'),
 PosixPath('../data/html/race/202508040304.bin'),
 PosixPath('../data/html/race/202509010708.bin'),
 PosixPath('../data/html/race/202305030201.bin'),
 PosixPath('../data/html/race/202408020505.bin'),
 PosixPath('../data/html/race/202403030207.bin'),
 PosixPath('../data/html/race/202405010709.bin'),
 PosixPath('../data/html/race/202308020808.bin'),
 PosixPath('../data/html/race/202506020510.bin'),
 PosixPath('../data/html/race/202509040411.bin'),
 PosixPath('../data/html/race/202507010101.bin'),
 PosixPath('../data/html/race/202401020609.bin'),
 PosixPath('../data/html/race/202409010808.bin'),
 PosixPath('../data/html/race/202304030201.bin'),
 PosixPath('../data/html/race/202404030111.bin'),
 PosixPath('../data/html/race/202405050504.bin'),
 PosixPath('../data/html/race/202507030607.bin'),
 PosixPath('../data/html/race/202504020303.bin'),
 PosixPath('../data/html/race/202308030606.bin'),
 PosixPath('../data/html/race/202507050302.bin'),
 PosixPath('../data/html/race/202404010605.bin'),
 PosixPath('../data/html/race/202405010411.bin'),
 PosixPath('../data/html/race/202504030201.bin'),
 PosixPath('../data/html/race/202405020803.bin'),
 PosixPath('../data/html/race/202402010708.bin'),
 PosixPath('../data/html/race/202302010109.bin'),
 PosixPath('../data/html/race/202405050309.bin'),
 PosixPath('../data/html/race/202306020204.bin'),
 PosixPath('../data/html/race/202508030209.bin'),
 PosixPath('../data/html/race/202408040708.bin'),
 PosixPath('../data/html/race/202307030303.bin'),
 PosixPath('../data/html/race/202310030609.bin'),
 PosixPath('../data/html/race/202308010302.bin'),
 PosixPath('../data/html/race/202507020601.bin'),
 PosixPath('../data/html/race/202404010807.bin'),
 PosixPath('../data/html/race/202508020810.bin'),
 PosixPath('../data/html/race/202309050207.bin'),
 PosixPath('../data/html/race/202404030407.bin'),
 PosixPath('../data/html/race/202506050506.bin'),
 PosixPath('../data/html/race/202506030702.bin'),
 PosixPath('../data/html/race/202507020408.bin'),
 PosixPath('../data/html/race/202309010711.bin'),
 PosixPath('../data/html/race/202408060109.bin'),
 PosixPath('../data/html/race/202307010808.bin'),
 PosixPath('../data/html/race/202408050309.bin'),
 PosixPath('../data/html/race/202303020501.bin'),
 PosixPath('../data/html/race/202405040805.bin'),
 PosixPath('../data/html/race/202403020602.bin'),
 PosixPath('../data/html/race/202505050404.bin'),
 PosixPath('../data/html/race/202301020701.bin'),
 PosixPath('../data/html/race/202502010808.bin'),
 PosixPath('../data/html/race/202301020312.bin'),
 PosixPath('../data/html/race/202303010408.bin'),
 PosixPath('../data/html/race/202506040112.bin'),
 PosixPath('../data/html/race/202407040606.bin'),
 PosixPath('../data/html/race/202505050106.bin'),
 PosixPath('../data/html/race/202310010110.bin'),
 PosixPath('../data/html/race/202408020402.bin'),
 PosixPath('../data/html/race/202506030601.bin'),
 PosixPath('../data/html/race/202505021103.bin'),
 PosixPath('../data/html/race/202505040702.bin'),
 PosixPath('../data/html/race/202408040510.bin'),
 PosixPath('../data/html/race/202304010510.bin'),
 PosixPath('../data/html/race/202507010105.bin'),
 PosixPath('../data/html/race/202310030612.bin'),
 PosixPath('../data/html/race/202306050208.bin'),
 PosixPath('../data/html/race/202509050511.bin'),
 PosixPath('../data/html/race/202507020508.bin'),
 PosixPath('../data/html/race/202303030604.bin'),
 PosixPath('../data/html/race/202508010303.bin'),
 PosixPath('../data/html/race/202509040908.bin'),
 PosixPath('../data/html/race/202310030412.bin'),
 PosixPath('../data/html/race/202305030204.bin'),
 PosixPath('../data/html/race/202309020504.bin'),
 PosixPath('../data/html/race/202306050310.bin'),
 PosixPath('../data/html/race/202410030311.bin'),
 PosixPath('../data/html/race/202408030504.bin'),
 PosixPath('../data/html/race/202405040204.bin'),
 PosixPath('../data/html/race/202410020307.bin'),
 PosixPath('../data/html/race/202509050708.bin'),
 PosixPath('../data/html/race/202310010401.bin'),
 PosixPath('../data/html/race/202502010409.bin'),
 PosixPath('../data/html/race/202304020309.bin'),
 PosixPath('../data/html/race/202508010602.bin'),
 PosixPath('../data/html/race/202410030609.bin'),
 PosixPath('../data/html/race/202507040402.bin'),
 PosixPath('../data/html/race/202406040707.bin'),
 PosixPath('../data/html/race/202408040609.bin'),
 PosixPath('../data/html/race/202508020802.bin'),
 PosixPath('../data/html/race/202510020703.bin'),
 PosixPath('../data/html/race/202508020603.bin'),
 PosixPath('../data/html/race/202405021209.bin'),
 PosixPath('../data/html/race/202304010707.bin'),
 PosixPath('../data/html/race/202310030106.bin'),
 PosixPath('../data/html/race/202506020306.bin'),
 PosixPath('../data/html/race/202510020202.bin'),
 PosixPath('../data/html/race/202509010309.bin'),
 PosixPath('../data/html/race/202305020409.bin'),
 PosixPath('../data/html/race/202307030703.bin'),
 PosixPath('../data/html/race/202307010511.bin'),
 PosixPath('../data/html/race/202508040611.bin'),
 PosixPath('../data/html/race/202405010208.bin'),
 PosixPath('../data/html/race/202306010402.bin'),
 PosixPath('../data/html/race/202509050109.bin'),
 PosixPath('../data/html/race/202507010607.bin'),
 PosixPath('../data/html/race/202405020503.bin'),
 PosixPath('../data/html/race/202408040106.bin'),
 PosixPath('../data/html/race/202504010803.bin'),
 PosixPath('../data/html/race/202307020302.bin'),
 PosixPath('../data/html/race/202303020307.bin'),
 PosixPath('../data/html/race/202308030208.bin'),
 PosixPath('../data/html/race/202507050603.bin'),
 PosixPath('../data/html/race/202401020104.bin'),
 PosixPath('../data/html/race/202308010805.bin'),
 PosixPath('../data/html/race/202506010611.bin'),
 PosixPath('../data/html/race/202304010101.bin'),
 PosixPath('../data/html/race/202509050401.bin'),
 PosixPath('../data/html/race/202306050201.bin'),
 PosixPath('../data/html/race/202305050108.bin'),
 PosixPath('../data/html/race/202307030808.bin'),
 PosixPath('../data/html/race/202305021209.bin'),
 PosixPath('../data/html/race/202305020507.bin'),
 PosixPath('../data/html/race/202305040701.bin'),
 PosixPath('../data/html/race/202402010606.bin'),
 PosixPath('../data/html/race/202406050809.bin'),
 PosixPath('../data/html/race/202404010701.bin'),
 PosixPath('../data/html/race/202309011206.bin'),
 PosixPath('../data/html/race/202507010811.bin'),
 PosixPath('../data/html/race/202507010712.bin'),
 PosixPath('../data/html/race/202510011005.bin'),
 PosixPath('../data/html/race/202509020710.bin'),
 PosixPath('../data/html/race/202509050312.bin'),
 PosixPath('../data/html/race/202405021103.bin'),
 PosixPath('../data/html/race/202409010401.bin'),
 PosixPath('../data/html/race/202306020805.bin'),
 PosixPath('../data/html/race/202410010109.bin'),
 PosixPath('../data/html/race/202507010302.bin'),
 PosixPath('../data/html/race/202503030312.bin'),
 PosixPath('../data/html/race/202410010204.bin'),
 PosixPath('../data/html/race/202503010503.bin'),
 PosixPath('../data/html/race/202504020611.bin'),
 PosixPath('../data/html/race/202407020807.bin'),
 PosixPath('../data/html/race/202508020202.bin'),
 PosixPath('../data/html/race/202509040210.bin'),
 PosixPath('../data/html/race/202410010501.bin'),
 PosixPath('../data/html/race/202303010211.bin'),
 PosixPath('../data/html/race/202408030303.bin'),
 PosixPath('../data/html/race/202505020701.bin'),
 PosixPath('../data/html/race/202306040203.bin'),
 PosixPath('../data/html/race/202505050111.bin'),
 PosixPath('../data/html/race/202307030608.bin'),
 PosixPath('../data/html/race/202306040206.bin'),
 PosixPath('../data/html/race/202403010603.bin'),
 PosixPath('../data/html/race/202408031205.bin'),
 PosixPath('../data/html/race/202403020210.bin'),
 PosixPath('../data/html/race/202501010506.bin'),
 PosixPath('../data/html/race/202309050903.bin'),
 PosixPath('../data/html/race/202503010301.bin'),
 PosixPath('../data/html/race/202406050102.bin'),
 PosixPath('../data/html/race/202507030103.bin'),
 PosixPath('../data/html/race/202507010602.bin'),
 PosixPath('../data/html/race/202404010409.bin'),
 PosixPath('../data/html/race/202405050101.bin'),
 PosixPath('../data/html/race/202306030403.bin'),
 PosixPath('../data/html/race/202309010802.bin'),
 PosixPath('../data/html/race/202405030402.bin'),
 PosixPath('../data/html/race/202508020501.bin'),
 PosixPath('../data/html/race/202408020304.bin'),
 PosixPath('../data/html/race/202309030109.bin'),
 PosixPath('../data/html/race/202508030508.bin'),
 PosixPath('../data/html/race/202308030503.bin'),
 PosixPath('../data/html/race/202304040610.bin'),
 PosixPath('../data/html/race/202505010410.bin'),
 PosixPath('../data/html/race/202408030603.bin'),
 PosixPath('../data/html/race/202305050111.bin'),
 PosixPath('../data/html/race/202305030510.bin'),
 PosixPath('../data/html/race/202310030503.bin'),
 PosixPath('../data/html/race/202306040102.bin'),
 PosixPath('../data/html/race/202401010505.bin'),
 PosixPath('../data/html/race/202304020411.bin'),
 PosixPath('../data/html/race/202502010102.bin'),
 PosixPath('../data/html/race/202503010306.bin'),
 PosixPath('../data/html/race/202407030409.bin'),
 PosixPath('../data/html/race/202505010603.bin'),
 PosixPath('../data/html/race/202404030312.bin'),
 PosixPath('../data/html/race/202301020812.bin'),
 PosixPath('../data/html/race/202307030301.bin'),
 PosixPath('../data/html/race/202504030402.bin'),
 PosixPath('../data/html/race/202403030112.bin'),
 PosixPath('../data/html/race/202309010805.bin'),
 PosixPath('../data/html/race/202310010509.bin'),
 PosixPath('../data/html/race/202509010801.bin'),
 PosixPath('../data/html/race/202304040609.bin'),
 PosixPath('../data/html/race/202507030109.bin'),
 PosixPath('../data/html/race/202509010709.bin'),
 PosixPath('../data/html/race/202505050604.bin'),
 PosixPath('../data/html/race/202506010505.bin'),
 PosixPath('../data/html/race/202507010305.bin'),
 PosixPath('../data/html/race/202506050708.bin'),
 PosixPath('../data/html/race/202305040111.bin'),
 PosixPath('../data/html/race/202404040808.bin'),
 PosixPath('../data/html/race/202308010102.bin'),
 PosixPath('../data/html/race/202310020211.bin'),
 PosixPath('../data/html/race/202410020604.bin'),
 PosixPath('../data/html/race/202301020202.bin'),
 PosixPath('../data/html/race/202301020507.bin'),
 PosixPath('../data/html/race/202402011001.bin'),
 PosixPath('../data/html/race/202309010504.bin'),
 PosixPath('../data/html/race/202501010810.bin'),
 PosixPath('../data/html/race/202408010603.bin'),
 PosixPath('../data/html/race/202502010505.bin'),
 PosixPath('../data/html/race/202405040501.bin'),
 PosixPath('../data/html/race/202301020604.bin'),
 PosixPath('../data/html/race/202306050610.bin'),
 PosixPath('../data/html/race/202309020704.bin'),
 PosixPath('../data/html/race/202406020111.bin'),
 PosixPath('../data/html/race/202509030504.bin'),
 PosixPath('../data/html/race/202304010805.bin'),
 PosixPath('../data/html/race/202407020205.bin'),
 PosixPath('../data/html/race/202403010201.bin'),
 PosixPath('../data/html/race/202506010101.bin'),
 PosixPath('../data/html/race/202403020407.bin'),
 PosixPath('../data/html/race/202409020502.bin'),
 PosixPath('../data/html/race/202310010101.bin'),

In [8]:
results=create_rawdf.create_results(html_path_list=html_paths_race)

  0%|          | 0/10365 [00:00<?, ?it/s]

table not found at 202506010604
table not found at 202408050402
table not found at 202404010605
table not found at 202408050309
table not found at 202403020808
table not found at 202404030601
table not found at 202506010704
table not found at 202510011105
table not found at 202403030411
table not found at 202509010401
table not found at 202410020705
table not found at 202407020506
table not found at 202408050605
table not found at 202407020105
table not found at 202410020704
table not found at 202510011104
table not found at 202405040203
table not found at 202403030203
table not found at 202407030103
table not found at 202408050601
table not found at 202403020501
table not found at 202408060604
table not found at 202408060506
table not found at 202408050304
table not found at 202404040602
table not found at 202404040101
table not found at 202403030603
table not found at 202407030601
table not found at 202406040704
table not found at 202403030104
table not found at 202405040108
table not found at 202408070602
table not found at 202404040406
table not found at 202408050707
table not found at 202407020801
table not found at 202408050404
table not found at 202505010412
table not found at 202510011202
table not found at 202403030208
table not found at 202408060402
table not found at 202407020501
table not found at 202503010304
table not found at 202510011203
table not found at 202510011204
table not found at 202406040407
table not found at 202503010602
table not found at 202410020804
table not found at 202407030501
table not found at 202510010702
table not found at 202408050712
table not found at 202406040503
table not found at 202507020302
table not found at 202404030704
table not found at 202406040906
table not found at 202410030601
table not found at 202408070305
table not found at 202404010604
table not found at 202408040202
table not found at 202403020504
table not found at 202405050412
table not found at 202404030701
table not found at 202408060202
table not found at 202408060606
table not found at 202410030709
table not found at 202405030211
table not found at 202401020809

In [9]:
#欠損チェック
results

,着順,枠番,馬番,馬名,性齢,斤量,騎手,タイム,着差,ﾀｲﾑ指数,...,調教ﾀｲﾑ,厩舎ｺﾒﾝﾄ,備考,調教師,馬主,賞金(万円),horse_id,jockey_id,trainer_id,owner_id
race_id,,,,,,,,,,,,,,,,,,,,,
202406010111,1,2,3,リカンカブール,牡5,56.0,津村明秀,1:58.9,NaN,**,...,NaN,NaN,NaN,[西] 田中克典,ラ・メール,4360.2,2019103823,01092,01180,877800
202406010111,2,4,7,ククナ,牝6,54.0,戸崎圭太,1:59.0,1/2,**,...,NaN,NaN,NaN,[東] 栗田徹,キャロットファーム,1717.2,2018105008,05386,01127,486800
202406010111,3,8,15,マイネルクリソーラ,牡5,55.0,Ｍ．デム,1:59.1,クビ,**,...,NaN,NaN,NaN,[東] 中野栄治,サラブレッドクラブ・ラフィアン,1108.6,2019100792,05212,01010,546800
202406010111,4,4,8,ボーンディスウェイ,牡5,55.0,木幡巧也,1:59.2,3/4,**,...,NaN,NaN,NaN,[東] 牧光二,平田修,650.0,2019104658,01162,01106,011008
202406010111,5,6,12,ホウオウアマゾン,牡6,58.0,横山武史,1:59.3,1/2,**,...,NaN,NaN,NaN,[西] 矢作芳人,小笹芳央,430.0,2018105192,01170,01075,906033
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
202408060704,7,8,11,ノーティアス,牡5,60.0,五十嵐雄,3:25.0,大,NaN,...,NaN,NaN,NaN,[東] 宗像義忠,吉田照哉,NaN,2019104908,01069,00420,758005
202408060704,8,4,4,ソルトロング,牡3,58.0,小野寺祐,3:25.5,3,NaN,...,NaN,NaN,NaN,[西] 木原一良,杉浦敏夫,NaN,2021102960,01123,01033,781033
202408060704,9,6,7,ホウオウエクレール,牡7,60.0,小牧加矢,3:28.8,大,NaN,...,NaN,NaN,NaN,[西] 宮徹,小笹芳央,NaN,2017103293,01196,01018,906033
202408060704,10,8,10,バルミュゼット,牡5,60.0,森一馬,3:37.0,大,NaN,...,NaN,NaN,NaN,[西] 藤野健太,ノルマンディーサラブレッドレーシング,NaN,2019106701,01139,01200,854800
202408060704,中,6,6,アーベントイアー,牡3,58.0,上野翔,NaN,NaN,NaN,...,NaN,NaN,NaN,[東] 水野貴広,ディアレストクラブ,NaN,2021103057,01087,01094,013803

In [10]:
#重複チェック
results.reset_index()[["race_id","horse_id"]].duplicated().sum()

0

## horseページからのデータの取得

In [21]:
horse_id_list=results["horse_id"].unique()

In [12]:
html_paths_horse=scraping.scrape_html_horse(horse_id_list=horse_id_list, skip=True)

  0%|          | 0/21735 [00:00<?, ?it/s]

skipped:2019103823
skipped:2018105008
skipped:2019100792
skipped:2019104658
skipped:2018105192
skipped:2017103201
skipped:2019102879
skipped:2016104711
skipped:2020105744
skipped:2015100744
skipped:2019105532
skipped:2017103751
skipped:2017104756
skipped:2020106967
skipped:2017102897
skipped:2016104319
skipped:2020105631
skipped:2021100980
skipped:2022105198
skipped:2022103703
skipped:2021105951
skipped:2022104897
skipped:2022100548
skipped:2020104744
skipped:2021106057
skipped:2022100650
skipped:2022100757
skipped:2019103204
skipped:2021101041
skipped:2022105076
skipped:2022100216
skipped:2022100604
skipped:2023102243
skipped:2023103904
skipped:2023106516
skipped:2023102132
skipped:2023100900
skipped:2023101278
skipped:2023105414
skipped:2023101484
skipped:2023105059
skipped:2023104993
skipped:2023104468
skipped:2023104379
skipped:2023103083
skipped:2023100684
skipped:2023106938
skipped:2023102474
skipped:2020102873
skipped:2020104739
skipped:2020105655
skipped:2020103648
skipped:2020102688
skipped:2020103655
skipped:2020105615
skipped:2020103255
skipped:2020109003
skipped:2020102563
skipped:2020103565
skipped:2020103928
skipped:2020101557
skipped:2020103225
skipped:2020105656
skipped:2019106251
skipped:2020103052
skipped:2018102151
skipped:2019106088
skipped:2019105341
skipped:2019105755
skipped:2018102144
skipped:2020105201
skipped:2018105030
skipped:2016102615
skipped:2020102646
skipped:2020100806
skipped:2020101268
skipped:2020106820
skipped:2020104034
skipped:2020101960
skipped:2020106354
skipped:2020103922
skipped:2020102342
skipped:2020105848
skipped:2020106044
skipped:2020105926
skipped:2020102409
skipped:2020103677
skipped:2021100081
skipped:2021105530
skipped:2021103534
skipped:2021106520
skipped:2021101180
skipped:2021102704
skipped:2021106537
skipped:2021106719
skipped:2021102353
skipped:2021101099
skipped:2020104561
skipped:2020105228
skipped:2020110100
skipped:2020110073
skipped:2020102349
skipped:2020103107
skipped:2020104360
skipped:2020100007
skipped:2020110092
skipped:2020106545
skipped:2020110152
skipped:2020100687
skipped:2020103258
skipped:2020101262
skipped:2019100677
skipped:2019104568
skipped:2018106612
skipped:2020104911
skipped:2018109046
skipped:2020100482
skipped:2020106821
skipped:2020105484
skipped:2018100773
skipped:2017101991
skipped:2018106601
skipped:2018103120
skipped:2018101215
skipped:2018106717
skipped:2020101737
skipped:2018102294
skipped:2020102377
skipped:2020102952
skipped:2020105137
skipped:2020103956
skipped:2020100733
skipped:2020105969
skipped:2020106013
skipped:2020105957
skipped:2020106898
skipped:2020103724
skipped:2020103178
skipped:2020100984
skipped:2020104359
skipped:2020106687
skipped:2020103281
skipped:2020107154
skipped:2020104154
skipped:2017101380
skipped:2020101707
skipped:2017101534
skipped:2019105972
skipped:2019110087
skipped:2019100297
skipped:2017106642
skipped:2018103362
skipped:2016104668
skipped:2020104824
skipped:2020101171
skipped:2020100759
skipped:2020104758
skipped:2020103243
skipped:2020110076
skipped:2020100441
skipped:2020106712
skipped:2020101536
skipped:2020100673
skipped:2020106895
skipped:2020102958
skipped:2020101992
skipped:2020103799
skipped:2020104333
skipped:2020105416
skipped:2022107149
skipped:2022106224
skipped:2022100384
skipped:2022103651
skipped:2022105395
skipped:2022106220
skipped:2022106705
skipped:2022104975
skipped:2022105000
skipped:2022107339
skipped:2022103073
skipped:2022103344
skipped:2022100064
skipped:2022105331
skipped:2022104837
skipped:2022105889
skipped:2020101607
skipped:2020104013
skipped:2019105239
skipped:2020103304
skipped:2020103464
skipped:2019100664
skipped:2019105995
skipped:2020103499
skipped:2019105091
skipped:2020104636
skipped:2020101572
skipped:2020102967
skipped:2020100433
skipped:2020103110
skipped:2020105165
skipped:2020102876
skipped:2020104227
skipped:2020105664
skipped:2020107044
skipped:2020102785
skipped:2020104394
skipped:2020100474
skipped:2020102714
skipped:2020106352
skipped:2020105750
skipped:2018105071
skipped:2019103012
skipped:2017104985
skipped:2018105398
skipped:2016102229
skipped:2019102496
skipped:2018102832
skipped:2019101261
skipped:2018105462
skipped:2020103348
skipped:2020105585
skipped:2021101399
skipped:2021106706
skipped:2021104131
skipped:2021105736
skipped:2021110084
skipped:2019101620
skipped:2020103550
skipped:2021100248
skipped:2019103400
skipped:2020110069
skipped:2018104713
skipped:2021100448
skipped:2020110116
skipped:2017103822
skipped:2021100301
skipped:2020105144
skipped:2020106408
skipped:2020103316
skipped:2020101632
skipped:2020102977
skipped:2020101764
skipped:2020101008
skipped:2020102843
skipped:2020102993
skipped:2020110151
skipped:2020103270
skipped:2020101020
skipped:2020100055
skipped:2020101795
skipped:2020106874
skipped:2020102641
skipped:2019102654
skipped:2020100761
skipped:2019106576
skipped:2020105456
skipped:2020107168
skipped:2020106571
skipped:2018104846
skipped:2018100822
skipped:2020106980
skipped:2019105915
skipped:2019102147
skipped:2019103897
skipped:2019101708
skipped:2018106200
skipped:2019104002
skipped:2018105201
skipped:2019103584
skipped:2018106366
skipped:2018103200
skipped:2017103323
skipped:2018104471
skipped:2018103262
skipped:2019105249
skipped:2019100986
skipped:2018104627
skipped:2017106776
skipped:2023101452
skipped:2023102036
skipped:2023106018
skipped:2023105274
skipped:2023106105
skipped:2023103592
skipped:2023101854
skipped:2023107418
skipped:2023103425
skipped:2023105467
skipped:2023106304
skipped:2023103418
skipped:2023105436
skipped:2023100935
skipped:2023106437
skipped:2023103032
skipped:2023106608
skipped:2023103256
skipped:2023101101
skipped:2023100006
skipped:2023102360
skipped:2023104699
skipped:2023104165
skipped:2023109094
skipped:2023101177
skipped:2023100421
skipped:2023109116
skipped:2020103086
skipped:2020101968
skipped:2020104525
skipped:2020101905
skipped:2020103001
skipped:2020101811
skipped:2020103308
skipped:2020105400
skipped:2020104136
skipped:2020103663
skipped:2020104426
skipped:2020106550
skipped:2018105471
skipped:2018100858
skipped:2020104148
skipped:2020102045
skipped:2018106473
skipped:2020101275
skipped:2019106671
skipped:2020100604
skipped:2017102877
skipped:2019100083
skipped:2019104726
skipped:2019102313
skipped:2020106063
skipped:2018106508
skipped:2022101250
skipped:2022100404
skipped:2022100655
skipped:2022102419
skipped:2022105279
skipped:2022106016
skipped:2022104546
skipped:2022103592
skipped:2021110033
skipped:2021106559
skipped:2022110012
skipped:2022106647
skipped:2021105491
skipped:2020104415
skipped:2022110112
skipped:2021102164
skipped:2023105037
skipped:2023104728
skipped:2023107149
skipped:2023105802
skipped:2023100951
skipped:2023105977
skipped:2023105745
skipped:2023101334
skipped:2023101979
skipped:2023104444
skipped:2023100902
skipped:2023110074
skipped:2023100286
skipped:2021105888
skipped:2021105487
skipped:2021104840
skipped:2021100402
skipped:2021102854
skipped:2021106067
skipped:2021101732
skipped:2021107002
skipped:2021100410
skipped:2021105614
skipped:2021100627
skipped:2021101614
skipped:2021100011
skipped:2021101868
skipped:2021101335
skipped:2021102668
skipped:2021106884
skipped:2021100353
skipped:2021105549
skipped:2019106821
skipped:2021104842
skipped:2020102798
skipped:2019100549
skipped:2020103939
skipped:2020103463
skipped:2021103506
skipped:2018110037
skipped:2021106785
skipped:2021105574
skipped:2019100790
skipped:2020106475
skipped:2020103803
skipped:2017105253
skipped:2022106395
skipped:2022100653
skipped:2022105021
skipped:2022104928
skipped:2022103059
skipped:2022106942
skipped:2022110093
skipped:2022102383
skipped:2022105569
skipped:2022103882
skipped:2022103766
skipped:2022101643
skipped:2022101480
skipped:2022103310
skipped:2022102722
skipped:2022103315
skipped:2022104194
skipped:2022105833
skipped:2022103537
skipped:2022103184
skipped:2022105227
skipped:2022105389
skipped:2022104623
skipped:2022106797
skipped:2022107250
skipped:2022101759
skipped:2022100525
skipped:2022106225
skipped:2020100979
skipped:2020104452
skipped:2020105873
skipped:2020105540
skipped:2020110120
skipped:2019101753
skipped:2019103219
skipped:2020106502
skipped:2019110076
skipped:2020102671
skipped:2018104310
skipped:2018104208
skipped:2017103167
skipped:2018103551
skipped:2018105495
skipped:2019102761
skipped:2018106553
skipped:2017100922
skipped:2018102593
skipped:2017103418
skipped:2017105070
skipped:2018105457
skipped:2019104869
skipped:2019101714
skipped:2019110015
skipped:2020103387
skipped:2020101579
skipped:2017104137
skipped:2017102952
skipped:2018101337
skipped:2017100992
skipped:2017100451
skipped:2017106125
skipped:2019100668
skipped:2018104729
skipped:2018104698
skipped:2017106012
skipped:2018104754
skipped:2018104575
skipped:2019104068
skipped:2019105544
skipped:2019103876
skipped:2019101887
skipped:2018104162
skipped:2018100413
skipped:2019102062
skipped:2016103386
skipped:2019106868
skipped:2019102364
skipped:2020105781
skipped:2019105383
skipped:2020104745
skipped:2020100621
skipped:2020105798
skipped:2018101300
skipped:2020102348
skipped:2020105273
skipped:2023105394
skipped:2023100207
skipped:2023100794
skipped:2023101557
skipped:2023106577
skipped:2023102706
skipped:2022110110
skipped:2022100102
skipped:2022104992
skipped:2022103775
skipped:2022103749
skipped:2022101826
skipped:2022104364
skipped:2022100013
skipped:2022100209
skipped:2022101238
skipped:2022101760
skipped:2022105939
skipped:2022101979
skipped:2022102362
skipped:2022106215
skipped:2022106323
skipped:2021100359
skipped:2021100822
skipped:2021103882
skipped:2021104297
skipped:2021102775
skipped:2021100680
skipped:2021104033
skipped:2021107215
skipped:2021105364
skipped:2021103762
skipped:2023103101
skipped:2023104430
skipped:2023102814
skipped:2023100910
skipped:2023110015
skipped:2023105103
skipped:2023106464
skipped:2023102144
skipped:2023102357
skipped:2023105587
skipped:2023104027
skipped:2023103723
skipped:2023105826
skipped:2023103654
skipped:2023106823
skipped:2023100936
skipped:2023105685
skipped:2023102889
skipped:2023104075
skipped:2023103036
skipped:2023103746
skipped:2023110066
skipped:2020106353
skipped:2020100867
skipped:2020106156
skipped:2020105310
skipped:2020101045
skipped:2020100769
skipped:2020105678
skipped:2020106388
skipped:2020105349
skipped:2020105876
skipped:2020105232
skipped:2020103847
skipped:2020102324
skipped:2020100050
skipped:2020105893
skipped:2019104750
skipped:2019104613
skipped:2016102904
skipped:2019100221
skipped:2019104674
skipped:2019104746
skipped:2018104791
skipped:2015105440
skipped:2019103663
skipped:2019105475
skipped:2018105207
skipped:2019104741
skipped:2019105440
skipped:2021106366
skipped:2021105033
skipped:2021107265
skipped:2021102424
skipped:2021101905
skipped:2021102053
skipped:2021100215
skipped:2021100480
skipped:2021105185
skipped:2021104006
skipped:2021106801
skipped:2021104025
skipped:2021110156
skipped:2020103876
skipped:2021103819
skipped:2021106637
skipped:2019102491
skipped:2021104649
skipped:2018105129
skipped:2019105241
skipped:2019103825
skipped:2020106409
skipped:2020101035
skipped:2019100871
skipped:2021107280
skipped:2020106913
skipped:2019103556
skipped:2021101121
skipped:2019104549
skipped:2019101562
skipped:2018100406
skipped:2018104561
skipped:2018100480
skipped:2018103103
skipped:2019100709
skipped:2019103200
skipped:2019103577
skipped:2019101031
skipped:2019102303
skipped:2018101825
skipped:2021102079
skipped:2021100685
skipped:2021104141
skipped:2021106246
skipped:2021100221
skipped:2021101591
skipped:2021104523
skipped:2021103782
skipped:2021106629
skipped:2021106707
skipped:2021102390
skipped:2021104859
skipped:2021100003
skipped:2021107227
skipped:2021103140
skipped:2020102805
skipped:2020103119
skipped:2021106209
skipped:2021106797
skipped:2020103520
skipped:2020106549
skipped:2020101377
skipped:2020100209
skipped:2021106910
skipped:2020103120
skipped:2019106954
skipped:2020101457
skipped:2019102728
skipped:2019101646
skipped:2021105348
skipped:2021105970
skipped:2021102379
skipped:2021104827
skipped:2021106897
skipped:2021103591
skipped:2021107047
skipped:2021103963
skipped:2021105047
skipped:2021105490
skipped:2020106873
skipped:2021100170
skipped:2019102143
skipped:2021105750
skipped:2018101989
skipped:2020103566
skipped:2020104708
skipped:2018110117
skipped:2021105120
skipped:2021101235
skipped:2020102161
skipped:2021110127
skipped:2021105831
skipped:2019106691
skipped:2020106552
skipped:2020105603
skipped:2018104512
skipped:2018105086
skipped:2018105336
skipped:2020106439
skipped:2020102725
skipped:2019103850
skipped:2019100768
skipped:2020103865
skipped:2019100861
skipped:2018104925
skipped:2020100382
skipped:2018104711
skipped:2019102937
skipped:2019107025
skipped:2020107036
skipped:2022104845
skipped:2022105456
skipped:2022104899
skipped:2022104856
skipped:2022105399
skipped:2022106228
skipped:2022104774
skipped:2022102209
skipped:2023102083
skipped:2023107304
skipped:2023101040
skipped:2023105271
skipped:2023103956
skipped:2023106119
skipped:2023103321
skipped:2023106482
skipped:2023101629
skipped:2023103634
skipped:2023106758
skipped:2023106300
skipped:2023103221
skipped:2023106395
skipped:2023106466
skipped:2023105422
skipped:2023105084
skipped:2023107113
skipped:2023106188
skipped:2023103532
skipped:2023106931
skipped:2023104960
skipped:2023100281
skipped:2023103160
skipped:2023104325
skipped:2023109040
skipped:2023105253
skipped:2023104192
skipped:2023106169
skipped:2021105283
skipped:2021110003
skipped:2020102982
skipped:2020101184
skipped:2020103530
skipped:2021102615
skipped:2021102388
skipped:2021105529
skipped:2020104477
skipped:2020102561
skipped:2020106798
skipped:2021101595
skipped:2020103209
skipped:2021102013
skipped:2021100564
skipped:2020103705
skipped:2021101651
skipped:2020103261
skipped:2021102755
skipped:2021101102
skipped:2019101985
skipped:2019101416
skipped:2021101650
skipped:2020103073
skipped:2021106298
skipped:2020103365
skipped:2020106344
skipped:2019106143
skipped:2021100683
skipped:2021101357
skipped:2019102593
skipped:2019104010
skipped:2019100663
skipped:2019103831
skipped:2017105358
skipped:2018101572
skipped:2018103437
skipped:2019110089
skipped:2018106715
skipped:2019103278
skipped:2018100755
skipped:2019103468
skipped:2021102244
skipped:2021102912
skipped:2021103742
skipped:2021100088
skipped:2021105062
skipped:2021106474
skipped:2021104519
skipped:2021100461
skipped:2021106256
skipped:2021106584
skipped:2021100385
skipped:2021101544
skipped:2021105696
skipped:2021102109
skipped:2021100071
skipped:2020101582
skipped:2021101457
skipped:2021103073
skipped:2020101641
skipped:2021101431
skipped:2020103189
skipped:2021100653
skipped:2018106561
skipped:2020104126
skipped:2020101853
skipped:2020103634
skipped:2021102845
skipped:2017100447
skipped:2020110118
skipped:2022105175
skipped:2022103243
skipped:2019105807
skipped:2022104930
skipped:2021100151
skipped:2021105214
skipped:2022102306
skipped:2022102167
skipped:2022105258
skipped:2022100220
skipped:2022100182
skipped:2022101256
skipped:2022106961
skipped:2022103526
skipped:2022106579
skipped:2022100988
skipped:2022105283
skipped:2022105239
skipped:2022105307
skipped:2022107409
skipped:2022109081
skipped:2022100374
skipped:2019105400
skipped:2017104238
skipped:2019104665
skipped:2019110084
skipped:2019105032
skipped:2017102758
skipped:2017101783
skipped:2018102041
skipped:2019104959
skipped:2018103993
skipped:2020105599
skipped:2018105164
skipped:2019101198
skipped:2019100630
skipped:2016101745
skipped:2018101087
skipped:2019105993
skipped:2018104059
skipped:2018103238
skipped:2019105537
skipped:2017105789
skipped:2018105251
skipped:2019105039
skipped:2021106171
skipped:2017104106
skipped:2018106532
skipped:2020101913
skipped:2020101465
skipped:2020102596
skipped:2020102987
skipped:2020105675
skipped:2020101264
skipped:2020103023
skipped:2020104920
skipped:2020103423
skipped:2020101323
skipped:2020105000
skipped:2020101075
skipped:2020101409
skipped:2020100936
skipped:2022107133
skipped:2022106040
skipped:2022105362
skipped:2022103052
skipped:2022102227
skipped:2022101254
skipped:2022103618
skipped:2022104438
skipped:2022103222
skipped:2022101137
skipped:2022104140
skipped:2022103457
skipped:2022102752
skipped:2022106117
skipped:2022107203
skipped:2022104972
skipped:2022100918
skipped:2022109115
skipped:2022103327
skipped:2022106418
skipped:2022107087
skipped:2022100207
skipped:2022106337
skipped:2022102493
skipped:2022106578
skipped:2022105947
skipped:2022103034
skipped:2022109152
skipped:2022103992
skipped:2018101966
skipped:2019100284
skipped:2019102583
skipped:2018106529
skipped:2017102510
skipped:2019110061
skipped:2019106425
skipped:2019100323
skipped:2017104944
skipped:2019102065
skipped:2021106986
skipped:2021110121
skipped:2021104954
skipped:2021103737
skipped:2021102105
skipped:2021101363
skipped:2021102233
skipped:2021103448
skipped:2021100125
skipped:2021103222
skipped:2021110038
skipped:2021103105
skipped:2021103368
skipped:2021104135
skipped:2021102132
skipped:2021105606
skipped:2021102259
skipped:2021101289
skipped:2021103575
skipped:2021101722
skipped:2021101391
skipped:2021100291
skipped:2021105500
skipped:2021100317
skipped:2021105101
skipped:2021105841
skipped:2021100977
skipped:2021104933
skipped:2021103982
skipped:2021106235
skipped:2021101019
skipped:2021104319
skipped:2021105289
skipped:2021101414
skipped:2021101584
skipped:2021101382
skipped:2021105231
skipped:2021103505
skipped:2021105171
skipped:2021103841
skipped:2021102586
skipped:2021102400
skipped:2021103076
skipped:2021102564
skipped:2021100022
skipped:2021102386
skipped:2021103059
skipped:2020105618
skipped:2020104472
skipped:2020105498
skipped:2020102574
skipped:2020105797
skipped:2020103561
skipped:2020105567
skipped:2020103112
skipped:2020102969
skipped:2020101691
skipped:2020102697
skipped:2020100119
skipped:2020104654
skipped:2020105691
skipped:2021105763
skipped:2021105734
skipped:2021104763
skipped:2021103500
skipped:2021101779
skipped:2021101317
skipped:2021101403
skipped:2021106443
skipped:2021103243
skipped:2021106444
skipped:2021104181
skipped:2021106099
skipped:2021106596
skipped:2021102974
skipped:2021107232
skipped:2019104720
skipped:2019103965
skipped:2019101794
skipped:2019103887
skipped:2016102446
skipped:2019101624
skipped:2020101481
skipped:2019106183
skipped:2020102872
skipped:2019107007
skipped:2019102203
skipped:2018102477
skipped:2020102639
skipped:2020104295
skipped:2021104856
skipped:2020101341
skipped:2021104754
skipped:2021101002
skipped:2021104850
skipped:2019102186
skipped:2021100059
skipped:2021101415
skipped:2021106800
skipped:2018100967
skipped:2019100915
skipped:2018102186
skipped:2017105616
skipped:2018105814
skipped:2019104126
skipped:2019100212
skipped:2019105564
skipped:2018102163
skipped:2015101386
skipped:2019106878
skipped:2019107075
skipped:2020101772
skipped:2018105085
skipped:2020103328
skipped:2018104837
skipped:2018105373
skipped:2017110086
skipped:2020103076
skipped:2019101185
skipped:2017102675
skipped:2019105060
skipped:2021100114
skipped:2021109043
skipped:2021101558
skipped:2021103754
skipped:2021104487
skipped:2021105907
skipped:2021102720
skipped:2021106000
skipped:2021101794
skipped:2021107119
skipped:2022104793
skipped:2022102516
skipped:2022101102
skipped:2022100785
skipped:2022100121
skipped:2022109165
skipped:2021104479
skipped:2020103208
skipped:2020103642
skipped:2021105285
skipped:2020104285
skipped:2019105111
skipped:2019104531
skipped:2021105164
skipped:2020100829
skipped:2020102932
skipped:2020100719
skipped:2020105933
skipped:2020101302
skipped:2020104832
skipped:2020100158
skipped:2020107126
skipped:2020102549
skipped:2020102937
skipped:2020100690
skipped:2020104365
skipped:2020100935
skipped:2020104199
skipped:2019105087
skipped:2019100659
skipped:2018104674
skipped:2018100693
skipped:2019102522
skipped:2017105321
skipped:2019105415
skipped:2019100653
skipped:2015103357
skipped:2017100461
skipped:2018105064
skipped:2017104873
skipped:2023107119
skipped:2023102991

In [13]:
#html_paths_horseが失われた場合はファイルから読み込む
if "html_paths_horse" not in locals():
    html_paths_horse=list(scraping.HTML_HORSE_DIR.glob("*.bin"))

In [14]:
#馬の過去成績テーブルの作成
horse_results=create_rawdf.create_horse_results(html_paths_horse)

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:101: DtypeWarning: Columns (29) have mixed types. Specify dtype option on import or set low_memory=False.
  base_df = pd.read_csv(save_path, sep="\t", index_col=0)

  0%|          | 0/21735 [00:00<?, ?it/s]

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105008

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105192

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017103201

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016104711

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105744

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2015100744

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017102897

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016104319

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103648

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020109003

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103565

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019106251

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103052

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019106088

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105030

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016102615

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104034

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101960

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103922

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102342

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105848

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106044

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102409

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103677

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021105530

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021103534

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021101180

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021106719

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102349

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103107

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104360

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100007

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020110092

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106545

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100687

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103258

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019104568

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104911

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017101991

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018106601

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101737

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018102294

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102377

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105969

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106013

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106898

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103178

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100984

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104359

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103281

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020107154

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104154

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017101534

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019100297

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018103362

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103243

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020110076

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106712

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106895

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102958

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104333

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105416

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019100664

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105995

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105091

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104227

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105664

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020107044

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102714

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106352

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019103012

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017104985

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105398

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019102496

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019101261

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103348

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018104713

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102977

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106874

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020107168

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018104846

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019102147

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019101708

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018106200

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019104002

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105201

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018106366

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018103262

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105249

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019100986

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018104627

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017106776

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104525

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103663

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106550

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018106473

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017102877

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019104726

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018106508

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021107002

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021100627

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021101614

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021101335

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021102668

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2022103882

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102671

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018104208

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017103167

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105495

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018106553

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017100922

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018102593

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017103418

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017105070

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105457

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019104869

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019101714

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017100451

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019100668

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018104698

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017106012

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018104754

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018104575

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019101887

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018100413

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016103386

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019106868

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019102364

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102348

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105273

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021100359

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021107215

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021103762

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105310

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105876

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105232

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103847

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100050

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105893

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019104750

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019100221

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105207

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105440

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021106366

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021105033

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021107265

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021102053

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021105185

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021104025

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018104561

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018100480

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019103577

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019101031

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019102303

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018101825

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021100685

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021106629

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021102390

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021104859

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021100003

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021107227

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019106954

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101457

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019101646

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021105490

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105336

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106439

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103865

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019100861

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018104925

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100382

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018104711

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.

[SKIP NO UPDATE] 2019100663

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019103831

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018103437

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021106256

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021100071

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020110118

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019104665

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019110084

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017102758

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017101783

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016101745

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018104059

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018103238

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017105789

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021106171

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018106532

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102596

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104920

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105000

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101075

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101409

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2022109115

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2022103992

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018101966

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018106529

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017102510

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019110061

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019106425

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019102065

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021102233

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021103222

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021103105

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021103368

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021104135

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021105500

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021105101

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021105841

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021104319

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021100022

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021103059

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105618

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104472

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105797

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105567

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103112

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102969

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101691

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104654

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021101317

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021104181

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019103965

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019102203

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018102477

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018100967

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018102186

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018102163

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2015101386

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019106878

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105085

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105373

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103076

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017102675

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105060

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021105907

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021101794

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021107119

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105933

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104832

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100158

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102549

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100690

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104365

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100935

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104199

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017105321

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105415

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019100653

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017100461

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105064

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017104873

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021101948

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021102039

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021106720

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021103540

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019102540

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019101139

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016105750

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105121

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018101299

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019101639

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016106262

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2015101804

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018101072

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019103960

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018100239

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019103946

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104663

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019104461

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105656

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017103688

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019101179

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105539

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104363

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020107091

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104933

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106007

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106057

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105374

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106032

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106162

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017100169

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019110125

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019102013

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016103101

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103700

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100407

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101727

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104453

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021106836

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021100293

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021107261

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021105492

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021106824

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021101178

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021106107

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021106793

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105271

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021110049

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021101933

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021100617

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021102044

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021106295

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021105222

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021105199

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018109080

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018106311

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019109100

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018103736

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021102825

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017104744

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018103574

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019103428

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018103121

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018102247

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018106285

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016103509

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2014110029

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018106471

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017101041

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018102464

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017101147

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019100855

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019102649

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103877

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018100401

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019100498

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017100752

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020109124

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019104715

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019104849

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019100617

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017100577

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021106615

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021105773

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021100825

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019102542

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103455

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105088

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019104646

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017101624

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105621

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019106565

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018103125

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019106598

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105214

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103471

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019102068

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019104764

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018104828

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021100490

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021109087

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105489

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018104857

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103728

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016102333

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021102981

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021103313

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021102588

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019104657

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017103278

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102321

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105388

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104921

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105419

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104556

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103081

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021100408

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021103326

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021104271

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021103693

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020110126

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017106279

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016110131

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105131

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105146

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020110005

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105161

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019103600

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017103827

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019101615

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018103117

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019103846

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018100298

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018104367

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105940

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019106862

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019102936

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019102535

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019104557

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021106914

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021102220

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021104682

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021110095

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017102170

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104302

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021106181

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021100649

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021107175

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021104921

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021104036

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2022104950

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021105217

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021106169

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021105566

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021106006

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019110007

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2022103230

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101797

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101823

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019100786

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103191

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103344

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101358

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103816

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105785

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101187

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105728

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104343

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101082

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018101214

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019106730

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101560

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018101817

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019103261

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018104971

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017101562

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104769

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100914

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104267

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104284

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020109099

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104029

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102557

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104579

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105154

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2022104128

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018101590

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105304

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019103513

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021104708

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103338

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101814

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019104882

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100219

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100413

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100448

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100672

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100243

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102606

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021106579

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021106556

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021104593

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021102216

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021104038

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105981

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018103997

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105056

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105291

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103882

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105948

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101868

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101047

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021104761

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021101819

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021106909

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021101655

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021101565

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019100740

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018106739

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018100722

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021105764

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021101453

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021105007

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021107369

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021105625

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2022105741

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021105872

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019100548

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106888

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105853

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101077

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106473

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104120

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016102723

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105105

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105575

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018106064

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018104706

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101057

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019104529

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017103165

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103070

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019103506

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103054

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018104910

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019103973

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019104730

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103661

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018104576

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019104057

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103368

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021102001

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019110073

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016103252

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018102665

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103405

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105328

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101983

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106560

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106762

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103780

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103095

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101123

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105938

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102261

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020109154

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102566

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102234

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106856

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019100643

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103667

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105766

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020110011

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104222

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102658

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101335

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106645

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100299

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106754

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105954

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106945

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104506

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100485

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105798

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019101605

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019104098

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021103967

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021106675

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021106817

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021106144

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021103815

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021100520

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106435

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106936

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017106319

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019106334

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016102109

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018106429

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017102178

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019103837

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019106586

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017100825

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018100971

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017104706

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2015104367

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019106750

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017105386

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105810

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018104266

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018100953

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017104690

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2022103543

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2022102511

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2022104154

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021104689

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021105471

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106547

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106795

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018103330

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017106374

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016105014

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019100437

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021105607

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019102411

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019101291

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018103035

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019101778

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018106153

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018103755

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017104659

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018104985

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019104884

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017104945

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105319

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105382

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021105949

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021103623

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019104600

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019100464

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019100693

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018100537

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105560

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019100787

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019110002

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017105471

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018104825

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105430

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019104872

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018100593

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019102518

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103833

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104856

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018104161

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018104558

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105301

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105421

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018104732

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017106232

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020110095

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017105339

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019100796

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102586

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018104787

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019100953

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105826

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101399

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018101671

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016104634

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103760

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018104571

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105284

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101214

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105091

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100018

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102404

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102727

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102597

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101154

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020110042

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103042

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100894

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018102264

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018102181

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018106345

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017100216

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017103319

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019104451

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020110137

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019110103

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019100451

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019106119

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021100717

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021102513

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021103921

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2022103121

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2022101503

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019103912

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019100097

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102093

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020107118

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104008

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106774

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105345

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105171

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018104929

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105084

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105084

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019107031

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100173

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101226

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105177

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105558

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101158

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105397

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103047

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103635

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100146

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020110041

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100267

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021101682

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021101456

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021100181

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021102563

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021101070

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2022106541

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019104550

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018104196

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017102171

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100743

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106845

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104756

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102979

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100752

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105883

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102297

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019104074

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018104240

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018100927

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017101792

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016110115

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017105600

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019106410

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017105582

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105020

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017105569

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105824

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019104831

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017101797

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017105613

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019104536

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018102338

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019110086

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101293

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106713

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100851

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105850

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021107222

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020109086

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105852

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106426

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104102

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101014

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100748

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102191

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104969

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100212

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101957

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105708

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101884

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104615

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019103136

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017101726

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105847

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019100038

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021103208

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021101922

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021105005

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021102782

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101717

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019104470

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016110158

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105611

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2015109076

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018106573

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017101829

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019102028

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016101938

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016104517

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018100905

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021102107

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021102026

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018103127

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2015104582

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016100569

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017100997

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017101730

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017104652

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016104335

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018100736

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017103255

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019103953

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101026

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106882

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019100618

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019104542

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019104537

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017103117

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018101796

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017102676

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105381

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017102892

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103692

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105072

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021105524

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021101831

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021107391

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021106378

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021103437

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021102827

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021107147

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021102239

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016104252

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017105375

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017104719

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017102946

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106944

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104970

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020107170

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021100017

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021103089

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021105031

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021103087

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021105809

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021102963

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021102799

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021103012

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102139

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105792

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101002

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102920

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104966

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104669

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105358

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102154

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106411

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019100635

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019104688

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019106419

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105073

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105872

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019109109

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105643

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018100185

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105296

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019100522

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017104666

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106767

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102685

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100202

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017102084

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017110123

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017106720

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017106387

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017104852

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018110045

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017105298

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2015104347

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017105443

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016103415

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2014102625

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017104253

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017100367

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016104983

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2014101827

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021102150

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021102821

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021104409

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021100515

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021103765

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104496

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105523

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018100421

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101856

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019104303

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016102368

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021110094

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021105366

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021110100

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021100507

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021103286

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021100885

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021102517

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021100990

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021101124

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018100440

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021110114

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021105731

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021103277

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021105018

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021102811

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2022103867

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2022104373

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2022102268

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2022102650

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106642

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104205

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019101930

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019106491

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2022103333

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103504

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100066

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102090

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105854

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103285

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020110047

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105731

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020109066

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020109168

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020110071

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100679

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101516

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103879

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021102286

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021110163

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021103869

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021103469

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021104163

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021109064

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105209

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105306

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105260

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017106570

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2011106610

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021105579

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021100018

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102120

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019103984

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103450

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021104179

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021102805

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021100406

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021100527

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105143

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105555

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019101874

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017101804

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018102077

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105508

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016100634

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101777

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103570

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102700

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100921

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103771

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105339

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020107072

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021109026

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021106500

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021104239

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103496

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105229

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105764

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021100189

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019104528

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018100247

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102818

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019104409

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019109082

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105790

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020107124

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018104626

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103698

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021106323

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102874

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101296

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100581

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105448

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103585

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102340

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103215

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102804

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102985

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018103517

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018104317

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017105636

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105550

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103629

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105469

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105120

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.

[SKIP NO UPDATE] 2020101775

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105628

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020107007

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017110172

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018102595

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019104841

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019106186

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016102032

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2015105276

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017101765

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019106151

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019102751

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102800

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019100584

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019102799

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018106506

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101742

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103319

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106636

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019104538

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102323

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019106935

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102526

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019106510

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102676

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017104215

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103787

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105531

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103324

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102829

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100426

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106952

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021100655

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021101941

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021105513

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021107153

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021105525

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2022103728

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106926

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100163

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019106623

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017103607

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102595

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106675

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105297

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019101819

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106986

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104350

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020110142

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105788

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105213

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102769

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021103870

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021100445

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021105158

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021106777

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021100560

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021100726

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021100117

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021105846

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021102292

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106309

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102810

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100939

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106978

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020110093

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100239

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018103301

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018103622

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2015101447

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017110069

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105204

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017106572

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017105662

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017110076

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017101540

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016100285

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104171

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021104702

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021101623

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106196

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100042

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102426

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020110036

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100701

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106330

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105139

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102438

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100324

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101715

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103115

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102393

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101362

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102399

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103719

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101700

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105021

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101109

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021100243

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021101680

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021106818

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021107079

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104228

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019100614

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018103147

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018102053

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019104095

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019101266

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017105408

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2015102127

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019104572

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017105285

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017101915

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105321

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2015100533

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2022102705

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021105435

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019104551

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102383

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105643

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106392

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103264

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103008

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018106492

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018102226

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018104611

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019102399

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2015106286

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018104578

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019106591

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019106471

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021101641

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105975

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105048

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105082

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100144

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102049

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018106357

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105338

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018106324

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018102131

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2015103983

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018106513

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018103565

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016102113

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016105048

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017104196

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019100804

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105059

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018101114

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102792

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104797

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021105003

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021101908

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021106590

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021104573

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100272

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105476

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019100567

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018103430

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106633

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102827

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101425

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104275

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104288

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100779

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105508

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103313

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016100617

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101252

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102108

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101683

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106086

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102074

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104312

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020110004

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021104968

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021109059

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021104743

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021100611

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021102242

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021105877

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020107117

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104443

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102837

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105559

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105837

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102282

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103940

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106227

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105931

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021105034

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021105854

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021100425

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021106880

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021100841

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021109031

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021102703

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019103553

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105631

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019102164

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019102192

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104754

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104902

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021106124

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021103673

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100636

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100231

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101534

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103442

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101013

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105360

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105379

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104424

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019104478

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019102460

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102562

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019100182

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102963

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100121

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021105827

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021101245

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103600

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102517

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104984

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103927

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100195

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102031

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103158

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101954

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101592

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017105567

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017104093

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105721

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018101924

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105334

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017101882

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105466

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102921

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019101645

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2022103790

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102790

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101938

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105292

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017101109

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017102751

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104190

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018110119

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017100005

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018104738

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019104579

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016100652

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019106716

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019106688

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019104958

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019104118

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019101673

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105379

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106928

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019102177

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105940

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019104119

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106200

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104520

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106286

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017106400

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105249

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105638

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019102850

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018103477

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018102062

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021102773

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021105797

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021105406

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021100877

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021103898

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021101205

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019106028

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019103902

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021103264

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021102362

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021100992

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021106269

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021100849

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021100924

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019106321

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019103008

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018106425

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019106173

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105507

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018101984

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2015104714

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102271

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105265

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102294

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019104733

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100160

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019106605

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105442

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105874

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021106657

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021102760

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021103728

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021102865

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021105392

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021104152

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021105096

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021106405

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021105205

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021105468

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019100667

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105103

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018103102

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105029

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019103905

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018101997

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019103020

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017100682

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017105277

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019101268

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016101058

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105008

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019100322

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105102

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018103186

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019101662

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018106563

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019104918

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019104644

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105301

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019101253

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105480

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102754

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101206

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105776

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102554

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100505

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105834

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019104769

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017103885

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018102585

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018106389

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017103020

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105124

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102833

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105736

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102494

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106696

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106695

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105309

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021103294

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017104665

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019103014

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017104345

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018100719

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105529

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017103722

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019101877

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019104929

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104527

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102797

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102114

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106840

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104072

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102773

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104646

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019104486

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019104729

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017104972

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019103004

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105991

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019104639

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019104328

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018100813

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105497

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018106254

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019106153

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019100962

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105113

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018102724

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019106572

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018104022

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018106380

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021100141

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021107204

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021101173

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019106608

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018106699

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021106450

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021102195

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021101075

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021105527

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102973

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105174

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021105263

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021100137

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021106644

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021100816

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021101781

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021104683

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018101970

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2015102942

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018101742

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105819

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016103409

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019104321

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105465

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021102277

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021101686

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021103347

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021106316

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021107113

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021102979

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021100204

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020110060

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106720

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105665

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104509

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101725

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2022105020

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105938

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018103027

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018104947

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017105354

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017110033

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2015104047

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021102766

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021104863

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021102839

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021100271

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021104621

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021104592

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021103289

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021104807

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021100282

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021102679

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105580

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100607

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101590

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018100373

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017104234

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106523

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020110019

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106893

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101151

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101580

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105547

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106711

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019106877

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019104776

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017105132

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018103242

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021102920

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021104117

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021102395

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017105460

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105573

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019103817

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021101914

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104563

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100287

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106069

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105077

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021103005

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100923

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101898

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100609

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103840

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020107218

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018102009

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100702

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019101716

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018110112

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019102820

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021100166

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2022100543

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2022103112

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018106386

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105315

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019102436

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018104559

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019100168

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100686

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019100772

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018101573

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019101262

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021105819

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021100097

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021100720

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021100196

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021101097

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021104096

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016100550

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105194

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021106203

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017105874

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021110016

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2022104298

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021101025

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021105870

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021106833

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021101745

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021102846

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021101126

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021103836

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103596

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105150

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101869

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105649

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102260

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103026

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105220

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103217

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105979

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017104682

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105137

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018103194

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021101294

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021101940

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021101715

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021103715

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021106288

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017104743

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105634

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.

[SKIP NO UPDATE] 2021101423

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018104011

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017104060

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2022102776

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019104982

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105345

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016100596

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016104435

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016106232

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017105214

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018104366

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019100177

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018110097

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019104768

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018102087

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105556

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018102290

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018104345

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018102584

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018104966

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017105308

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018102090

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017105055

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021107116

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021101771

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021101835

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021102327

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021109155

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021100154

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021105708

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021103811

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021101626

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021102167

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021102258

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021103143

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021106475

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021105550

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021104318

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021103683

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021106083

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100443

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018102069

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103418

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016102929

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019106369

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2015103340

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105135

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021105351

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021106406

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018110021

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019103016

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017103353

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019101122

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019106885

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019104106

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018102204

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018101626

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021105301

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021100069

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105055

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100390

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103030

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105677

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020107173

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104817

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103211

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106962

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100732

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100298

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100668

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103254

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105187

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103098

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106584

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103478

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020110043

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104281

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102551

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021105297

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021102530

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021101852

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021105024

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021101202

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017102294

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017101415

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021102987

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021101790

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100458

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020109047

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103231

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104657

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101309

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021105475

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021104633

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103300

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105658

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104635

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103146

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102249

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2022100090

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019106099

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016100930

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103237

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020109092

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106515

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103327

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103057

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106517

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103465

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101376

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105404

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021102060

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021106564

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021100188

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021109097

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021103147

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021102403

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021102685

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021106672

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021106037

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017106264

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2012100683

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018102270

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016110085

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103622

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105628

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019104567

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102765

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105719

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102272

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102948

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102975

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102900

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020107119

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100993

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106669

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103309

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105569

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101896

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105332

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105888

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100949

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020107107

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105004

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021103245

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021106453

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021106975

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021102229

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021106470

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105383

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101574

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019102481

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021106069

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019104968

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018101943

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018100671

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105454

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105056

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019102531

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016106292

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021103318

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106733

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019103578

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105237

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017106087

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016105734

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018104949

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017103105

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016104227

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017100197

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018100025

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021105515

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021106322

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021105935

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021109010

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021106173

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021101988

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104122

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020107096

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100014

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106615

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104358

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105545

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016105060

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103271

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018104665

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2015100274

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018101245

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019104926

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017106230

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016100106

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017105126

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019109094

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019110066

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017101777

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018106305

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018101103

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018101946

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103693

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103437

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020110122

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101948

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101312

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104355

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101840

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103480

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020107147

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105063

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105358

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102990

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021102302

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021107350

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021101152

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021103458

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103416

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105343

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100773

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100709

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101986

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106410

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103843

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017100141

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105983

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019104607

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018104843

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016104998

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019107033

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101354

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104980

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105062

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105315

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105409

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106982

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103633

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103420

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021103750

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021110010

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021105172

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021100665

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019100791

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019100765

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105366

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105574

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104942

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104954

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100642

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102972

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021103039

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105500

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017100440

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016102044

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019101529

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021110006

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021110102

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019100126

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105040

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019101670

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101807

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100460

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106794

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103015

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101336

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104463

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018100096

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017106084

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019100629

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100162

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019103472

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103686

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020109071

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106334

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020110066

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104852

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021105361

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021103518

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021105815

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021100562

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021102951

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021100111

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021105914

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105458

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018104517

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021101630

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021106774

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021105303

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021101162

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021104528

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017101230

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104937

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100302

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106036

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020110067

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018104502

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019101002

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105238

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018104944

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105505

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021102254

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021106943

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021102833

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021106886

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2022104101

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106337

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106699

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102684

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100791

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101248

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106142

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018106569

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019106593

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021106773

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021105153

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021103159

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021110091

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021110070

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101251

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100440

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105044

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101698

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104816

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018101642

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105317

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021103659

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102219

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100154

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103481

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101122

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104787

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020110038

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101606

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100124

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019110090

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105023

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018103537

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018102202

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019100612

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105515

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019104924

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021102278

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018106145

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101247

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016101650

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105357

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102887

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105979

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106540

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104897

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106065

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103793

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100010

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104487

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104134

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018104908

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019102824

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103599

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018101452

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017104138

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018104936

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016101153

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105223

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018103084

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018100652

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017110041

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017101248

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019101903

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017104067

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017103895

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019106866

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017100468

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017105834

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018106211

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016105601

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017102270

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017105483

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017102808

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017100006

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100865

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105251

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101821

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105538

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021105835

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021107156

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021105437

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021101063

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103435

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017105587

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021102677

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021105204

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018100433

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019104738

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018100378

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101398

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106801

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105115

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021102046

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102796

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100677

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105645

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100354

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019100622

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018101551

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105711

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021109170

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021109127

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021109129

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021109112

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021109136

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021109121

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021109169

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021109154

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021109138

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019104522

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018102608

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105139

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017106086

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019100935

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017102037

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017105437

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103694

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105161

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106854

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021103599

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021101484

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102542

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021105962

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019110031

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019110021

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019106333

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019106590

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105314

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105515

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018106379

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018100483

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021103910

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021101823

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021105810

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2015110073

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021101903

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021103983

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021104967

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018103486

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2022104931

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105285

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103735

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021102331

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021100919

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105306

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103451

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104642

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100270

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102124

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102314

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106932

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104728

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021109137

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105144

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019101454

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018104762

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105518

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019100324

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021104161

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021105538

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021106558

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018100394

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019104976

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016104431

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018100570

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018103086

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105846

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105766

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021105824

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021106979

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021101566

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021105676

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021100223

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105525

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018101134

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019106060

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018100595

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019106149

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019102264

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018106276

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105163

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018100397

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018109052

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018106455

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105514

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018104643

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019101609

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018101210

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016100288

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018110095

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105450

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105364

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105679

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100900

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102799

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021106490

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105219

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105283

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016104877

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018100274

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017100041

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105183

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021105038

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104344

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101904

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103907

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100079

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106907

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104927

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106717

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021100927

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018104607

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105286

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105046

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105722

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019102220

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019104483

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019104496

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105151

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019102742

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018100985

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018103303

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017100081

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019106894

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102633

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104468

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102435

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103721

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019103309

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021103372

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021104518

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021102051

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021104207

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019110013

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101088

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018102133

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100369

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105740

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104993

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103136

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100381

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101603

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103564

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101426

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102230

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104294

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102893

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018102279

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020110130

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102936

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101210

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020107149

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105475

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019106596

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017105179

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018103206

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105365

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100039

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105136

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101112

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101360

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103869

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101722

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105495

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016100305

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018100387

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021110074

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021102916

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2022103947

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103546

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102577

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101825

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105896

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021100412

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021101816

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021105223

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021101856

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021106557

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100208

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101385

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020107098

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106734

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020110010

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101799

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100797

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2022100049

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2022102792

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2013104030

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2015105583

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2014103896

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019102005

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016105367

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019100574

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018106602

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019100731

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105258

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017105643

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018104533

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017102990

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017101761

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018106472

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018100188

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018106469

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019102112

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019103120

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019101917

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017104258

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021104533

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021101524

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018100389

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020110153

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018101514

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105256

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019101752

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017110146

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019100688

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021100098

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021103949

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021102334

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103288

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103613

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017103992

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021103969

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104467

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100481

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105805

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105274

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101965

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105832

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103814

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106859

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104836

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104518

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102104

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020110149

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020110113

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021104316

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021107273

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019100943

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017100654

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2015102390

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2015104571

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016101093

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016104729

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018104518

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102195

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105842

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018110137

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018102158

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101708

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105134

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018102586

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102571

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102540

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019103673

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105634

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103583

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020110054

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100783

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100841

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021105542

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021105795

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021105174

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017104270

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016100298

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105259

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018104233

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017102914

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2015100416

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018100530

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017100218

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018104894

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100734

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106582

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103472

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103413

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106867

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104830

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105215

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104266

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106860

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019104703

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2015106165

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2022100302

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020110080

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103623

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105868

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101541

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103134

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105047

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101397

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020110003

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103044

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019103418

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105070

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100755

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103829

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100340

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101200

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102655

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105638

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021101455

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021101055

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021102042

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2022105223

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019106104

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018100186

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018106162

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105433

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103543

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016102412

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021100947

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019103370

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105166

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105595

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101207

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019104937

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017103890

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100269

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100638

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019101618

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105285

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103196

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101819

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105069

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019100153

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017101121

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017100643

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102378

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105329

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018100756

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019104962

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106706

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019103123

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019106979

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019103769

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017104888

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2022105050

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019102611

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2022106490

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019110130

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019102159

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104109

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2015104707

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018104675

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017106071

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019106696

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016105502

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105419

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018106058

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019103064

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018104687

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018101928

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016102305

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019100642

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105224

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018100997

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020110059

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103798

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021103806

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021104193

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021103070

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021104951

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016104519

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104940

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021103972

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021106813

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021103465

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021104925

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021110086

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021101360

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019100841

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101931

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018104621

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021104938

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021102675

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021110045

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021101787

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021106141

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021104629

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021106838

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021105780

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017104052

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018101956

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019104516

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105176

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019106737

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105025

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105184

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019100685

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105436

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106637

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103617

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106671

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103163

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104894

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105100

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102451

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102322

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106201

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018102372

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100142

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018104477

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101703

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021102686

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021106812

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104919

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103207

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100793

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104811

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101381

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103702

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017106032

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021105825

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021100173

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021105945

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021100812

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021104753

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021103132

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021106222

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021100707

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021105147

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021104559

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021103447

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021104293

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021104602

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019102772

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100941

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021102518

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021107304

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021101820

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017102848

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019110055

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2015105033

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018102807

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021105365

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019102758

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019102066

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018106078

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021101631

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021110089

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021104165

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021102853

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021106354

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101396

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105350

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018104669

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105833

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105133

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019102059

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019101667

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019102737

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016100546

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017104129

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017100531

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017106018

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019103149

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019103017

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105528

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021102968

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021100741

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100343

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018101519

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018104946

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018103932

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018100994

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017105257

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017105181

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018104121

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021102568

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019101691

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019102568

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018106621

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2015103138

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018100827

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019100777

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019106707

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102591

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102312

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100026

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100674

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106903

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104018

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104103

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102813

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103430

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100981

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021102627

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021105170

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2015100822

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018100032

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101400

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019106582

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019104520

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021106372

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018106152

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018103181

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018102551

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019104954

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016100927

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017102095

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105105

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105593

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106682

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019106682

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018110110

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018110100

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019103071

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019101241

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021102917

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021103068

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021100510

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106338

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018110070

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017103485

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018101498

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2015110028

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2015104010

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018100173

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017106037

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2014100583

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105412

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019103814

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018102669

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018104077

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018103933

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018104780

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105105

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105212

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101921

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021105268

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021100640

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017103785

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017104783

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018110091

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018106697

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019104307

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016102197

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016110152

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017105541

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016103143

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2015105850

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2015101028

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018104029

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016104787

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019103040

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105107

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018100037

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019101744

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018104511

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021103900

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105460

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019104346

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019104239

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105968

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2015106125

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017110074

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105061

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2022101988

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019104629

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018104788

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018100255

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017103174

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016104451

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105033

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016104397

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017105331

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106968

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103265

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105348

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019104410

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021110157

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021102851

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021109046

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.

[SKIP NO UPDATE] 2019100055

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018102651

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105713

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019102783

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018103618

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019103440

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105906

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019101776

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101620

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105498

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101212

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018104070

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106818

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100450

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105059

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100819

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106747

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100030

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021104989

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103894

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101395

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105654

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106333

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104773

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021105188

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021103524

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021105592

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019103791

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018109002

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018104796

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021105472

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019100593

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105817

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019103705

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102123

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021106636

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021102600

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104499

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106207

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020109006

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102825

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100691

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020110025

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102789

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100539

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101510

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102069

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021101608

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021100570

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103322

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019104700

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103458

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101343

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016105171

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106701

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104598

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101724

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020109088

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101615

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021100743

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021100349

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021106317

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021103905

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021106736

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019102874

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100237

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101555

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103488

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106731

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100425

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106484

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103106

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018104938

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104163

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102879

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021102381

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105566

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102560

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100844

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100521

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020107049

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105423

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103498

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102644

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101156

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021106425

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018104913

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2022104672

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021104634

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021106319

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021107064

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021102124

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105647

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102634

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105712

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101238

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100292

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105355

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018110007

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2022105240

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021106131

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021106148

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100480

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101890

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103018

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100552

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105877

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017100452

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017110173

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2014103514

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105317

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017101700

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021104526

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021105627

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021104714

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105187

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019101267

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105469

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019109159

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103089

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105529

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103417

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019106370

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018106426

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021105441

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021106093

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104831

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103484

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020107183

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101740

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2014105947

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017105241

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016104921

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016102192

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018101643

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105418

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2015104713

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105365

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018103559

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019104978

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105081

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017101431

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018101071

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2014101985

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017103309

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019101032

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019106964

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2022105992

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2022100473

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021103980

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021104679

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021102990

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021105341

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021101293

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2022104148

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019103726

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018104406

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018100623

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018104879

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100731

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020107191

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105085

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100937

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019106929

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021109013

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019110051

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017101771

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105976

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102930

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102407

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104516

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103712

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019103563

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019101021

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105935

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018100636

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102940

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019103137

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019109140

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103372

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019100759

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019104462

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2022102711

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016103444

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105391

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018100600

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019103829

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021101407

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100730

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020110078

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020110091

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020110072

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106009

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106931

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104952

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105184

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102991

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020109125

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101996

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018100618

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018103377

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018102176

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105327

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019101677

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017105940

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019103301

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018106044

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019104995

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019104969

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019106363

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019102505

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105194

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106693

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105775

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021103444

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105226

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019102888

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019100390

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018106467

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018104786

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105083

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018104263

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100964

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102601

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100972

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105191

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103236

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105174

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017104068

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2015101707

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105264

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2014105531

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018103407

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018103615

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2014102449

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103769

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020110013

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019106677

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018102172

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017100811

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021101283

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021106287

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2022102791

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021103590

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021100545

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2022100778

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019101635

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019101421

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017105628

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105695

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021102387

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2022101931

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105101

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100118

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103273

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100290

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103174

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104461

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019104345

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019104717

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019104901

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018101296

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019102860

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021105783

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103266

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020110109

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021105685

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021101101

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021102179

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021102426

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016105206

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017104104

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018101516

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018100443

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2015100548

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105325

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102716

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100400

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017104623

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105644

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103645

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021102157

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021101552

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021104451

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106185

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100057

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104666

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100140

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021105149

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019103133

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019100637

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018102666

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105064

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2014102394

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018102953

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016102556

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2015105399

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018103204

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102849

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018100241

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017103493

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019101413

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019101151

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021105852

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021102011

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105492

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105340

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021103656

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106644

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106736

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106537

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100329

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103775

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105777

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016102483

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105367

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105337

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017106231

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016102111

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103250

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102667

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102980

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105146

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017104677

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019106858

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019104837

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021100821

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017101805

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017101186

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102181

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016104845

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102755

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017100808

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021103468

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019104610

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017103334

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017101763

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021109004

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021105403

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016104677

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019100736

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018104700

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019100152

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105461

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101540

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100890

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021105352

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019104259

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019109047

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101316

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102390

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101384

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021105855

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021107040

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021100777

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019110045

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017105531

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017105477

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018106545

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103466

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016105526

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016102201

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018104803

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2015101654

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105343

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016104556

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102747

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105791

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105833

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105780

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103343

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105851

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106815

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101420

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021105407

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021103352

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104320

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101542

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104347

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103568

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020110077

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017106366

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105402

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020110148

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104574

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104659

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103934

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105963

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102403

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100564

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105864

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2014105582

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105743

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016104632

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105474

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017102406

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017105106

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017105590

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2014100063

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019102009

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100295

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018102580

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018104980

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105165

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104528

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103753

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101998

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020110032

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020110098

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101514

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020110138

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105392

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017109123

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021105793

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021106573

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2015105868

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103386

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017105269

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2014106286

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021100460

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021102368

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021106842

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019100898

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100181

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103447

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104522

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104232

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100845

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017104606

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018102716

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017103677

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019103774

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019100292

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105499

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105144

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105175

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018102173

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018100226

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017104781

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021101169

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021106538

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021103974

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021106007

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021103189

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018104148

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017104164

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018104439

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018103391

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018101964

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106890

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103567

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105244

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102463

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105596

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106387

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106238

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101990

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100974

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105356

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100023

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100925

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020110086

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106210

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021104837

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021106321

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021105507

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021101467

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021106807

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021102786

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021106632

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021107054

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021106963

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105305

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018102149

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019104705

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017100251

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019101882

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019104997

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106730

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103239

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104821

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106301

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101643

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106038

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101629

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018102649

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018102831

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019101763

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016100455

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018100377

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016100507

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019103948

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105300

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101653

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105543

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104847

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106073

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102892

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103952

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017105282

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017101124

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105439

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017105522

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018104563

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021105000

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019101953

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017104478

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016106395

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2015105451

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021110064

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021101213

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019106895

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103605

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018103276

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021106132

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103531

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102309

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017105402

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018104833

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018100430

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2013103941

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018102287

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105408

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021104793

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019104735

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017104560

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018100748

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106862

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105129

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100352

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105565

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020109134

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103267

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105777

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021105878

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021105669

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021104781

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021106783

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021101661

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101219

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104686

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100753

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021102589

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2022103157

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103311

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106672

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018104874

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101640

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105322

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105305

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018102417

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019106690

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016102733

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017105379

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017104917

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019104706

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017105525

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103804

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106155

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020107217

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021105561

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021110009

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021104048

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103426

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020107033

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101798

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021101013

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021105572

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106046

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105562

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106170

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100500

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019104491

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017100436

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2013106055

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018106158

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102855

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105101

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017103886

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018104756

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105076

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016105292

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2015106423

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018100040

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100370

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104976

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100657

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102998

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103454

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100037

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102169

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103204

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019103858

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021106179

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021104027

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105324

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102145

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106714

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100424

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017100368

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105211

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105035

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018101746

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2014106348

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103706

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020110087

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104854

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101871

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021106352

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021105212

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021105733

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021103233

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021107302

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021103024

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021106433

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017104670

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019104721

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105103

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019102457

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105396

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019104426

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019100732

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016104887

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018103499

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2015105032

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021110083

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021106414

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021105304

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018106383

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019103656

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018109102

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104674

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021107042

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103581

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106011

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102931

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104223

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101539

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106298

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020107051

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104156

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021110101

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021103336

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019104896

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017110026

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017105422

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103525

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100933

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103197

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103315

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104514

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103717

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101721

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105360

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019104455

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105108

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019101276

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019106226

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021105458

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021105751

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021105924

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104625

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103548

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103586

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105521

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016104851

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019103407

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019106744

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021105937

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019101680

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106561

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2022104183

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101221

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101647

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106285

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101037

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105336

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106197

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017101536

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021103758

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021104975

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021105314

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021103899

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100808

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100676

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104255

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106716

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103651

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102507

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102043

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017105287

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018109095

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021105844

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021106397

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2014103963

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018100700

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104849

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102766

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106887

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105283

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102240

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101260

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102267

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102103

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103884

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102444

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018110087

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019100438

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019104524

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018104885

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019102785

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019102957

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103515

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021104150

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105349

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018104537

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017104727

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019104961

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019104467

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019100682

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019103096

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021107286

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021101786

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019103274

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017101376

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018104525

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102832

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021109128

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021104969

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021107234

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021103494

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021110113

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021100175

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021101616

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105624

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100726

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105845

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104545

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103038

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105932

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103761

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020109083

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102402

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101903

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017104691

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019100205

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018104914

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016110103

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101863

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103681

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102877

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104604

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016105715

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018103278

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103412

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103883

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104069

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103908

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101041

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101119

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105684

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106225

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021100295

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021105710

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018106806

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019102235

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016100764

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105232

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019110042

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019110064

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105444

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018110123

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018100757

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2022106431

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021101049

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021101838

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017100392

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105570

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103660

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018101553

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017103084

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019101910

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021107238

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021103324

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021102243

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021100458

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018106837

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105339

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018104340

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017103104

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2015103210

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101860

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105202

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021100983

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019110056

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106260

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106263

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102041

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102257

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101027

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102244

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021104458

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021105405

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021103496

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104766

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106146

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021104571

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021106795

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103079

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103899

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018101455

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106876

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101370

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100799

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016102668

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016105770

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018109129

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018100126

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2022110095

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019100108

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017105910

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018103446

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018101722

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2022110007

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018106511

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016100614

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2015105573

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102430

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106374

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100128

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105920

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100728

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021105494

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021105445

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021104741

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021104433

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021101327

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019100029

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018100580

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019107011

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103108

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104961

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102556

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104001

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020109104

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106190

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104292

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019103280

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019101275

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018103135

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018104880

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017102984

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105204

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017102518

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017103437

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103923

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021103013

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105253

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2022103849

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021106626

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021105071

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021102545

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102121

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104406

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100113

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019101626

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019100425

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102598

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103229

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102678

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106723

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105537

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019103633

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104490

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105953

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102915

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021102139

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103832

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019104459

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105802

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103959

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100725

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018110113

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2022106248

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018101994

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019101750

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018102815

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018103264

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105424

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017110129

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021100182

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105011

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100364

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103990

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106520

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021106955

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021104517

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101966

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101124

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104741

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105787

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100120

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105486

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017110006

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017101525

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104740

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020110045

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017105089

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105203

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017105367

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105784

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105059

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2022105420

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018100494

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021106703

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021101448

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021101261

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021103577

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019103661

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017103123

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102726

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100005

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103953

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018102328

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017105198

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018102943

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106933

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021100931

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017100167

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105169

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101286

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103849

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104054

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105811

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018104154

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016101493

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018104395

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019104518

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016104340

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021103072

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016101149

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017106115

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2015100493

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018106504

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016102534

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018102021

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017101722

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018104420

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021104739

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019102274

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100760

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100602

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106567

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105357

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021104495

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017104849

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017103023

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105493

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105130

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019104493

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021100149

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021102831

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105554

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018104364

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021102043

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021106671

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105342

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016105216

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019103099

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017105323

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021100506

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021103337

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105159

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021106214

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104541

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102698

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102722

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103824

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103206

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100136

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019101273

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018100577

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021101768

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017105591

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105887

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105763

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021104691

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018104688

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019104046

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019101793

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018106110

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021101168

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021103638

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021106989

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2022103831

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102593

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100641

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018104984

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102545

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101774

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106247

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100969

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021104370

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021100973

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106844

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103131

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103988

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018106172

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017103569

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2013105125

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018104150

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019106627

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018102117

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019103038

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018104262

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016106047

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017103341

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105901

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100922

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101748

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105369

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021105950

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101818

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105588

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101083

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103765

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103597

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105594

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104534

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101605

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106451

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105685

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018101255

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017103276

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018190005

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102264

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103332

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101847

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104048

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103890

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102176

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021100414

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021106407

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017105558

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018106588

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105548

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100868

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104672

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020107040

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103695

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105019

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017105517

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104660

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100167

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101040

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103789

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2022102361

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020110144

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104084

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103857

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020110143

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105464

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101282

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100361

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106070

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105317

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020109075

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105074

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017102936

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016105681

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016106518

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101432

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021106198

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021106877

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021106638

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021106875

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021103460

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021104166

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019104984

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017104095

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105331

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018103079

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018106157

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018100403

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021104506

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017101919

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018100808

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018104239

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017100416

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019102856

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021105409

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017104963

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018100395

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021104795

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2022105993

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105483

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104349

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102328

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021101772

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021102620

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021109025

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021106364

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105043

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018101345

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105370

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105235

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017100478

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016105042

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103802

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101854

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105318

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106700

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105405

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018104596

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018104640

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019100546

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105266

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2014100566

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021107199

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106917

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102295

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102742

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106525

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021100970

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101225

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100034

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020110102

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103557

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104017

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101915

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021109122

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021109135

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021109120

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021109146

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100692

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020107050

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106592

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103592

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103145

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101159

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018101216

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019103762

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018101006

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019103207

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019100144

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018104730

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019103548

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017104082

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021104322

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021101303

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106223

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105687

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101369

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100531

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102058

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101504

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103059

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105298

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105044

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102938

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018101804

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100800

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019110118

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105583

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019100652

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016104691

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101363

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104827

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103310

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103342

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105917

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106715

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103588

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103056

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020109090

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102749

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102149

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105179

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106425

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105620

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2022104993

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101139

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105316

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018100654

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019110011

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019101666

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017103942

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018104601

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021107218

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021103523

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021104620

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021106679

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106012

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021105093

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105195

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017101556

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021105151

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017100240

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019102788

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019103782

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100570

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106434

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105855

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102243

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017103328

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105965

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017102855

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017104674

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021103853

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021101040

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021105905

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021102367

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016104952

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102854

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021104980

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102903

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017104850

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018106411

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105379

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021103707

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021104187

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018104663

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018110136

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105128

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2015105401

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019103915

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018104835

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017105448

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019106629

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019106038

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018104152

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105420

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103394

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104862

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100975

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104356

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103861

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021105674

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021105256

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021110129

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021100374

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021104425

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105303

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101975

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105676

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019100910

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100045

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104480

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105871

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103133

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101867

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103190

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019103013

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018101945

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017105350

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017104688

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105226

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019102775

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017105584

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105272

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016105487

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021106517

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021102222

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021105200

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021106341

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105637

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103382

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103427

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105426

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021101502

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101710

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019102731

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021104109

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021102507

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101959

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020110154

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021100745

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021106195

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021104970

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017103814

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017100437

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021103826

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105005

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105947

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017104851

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017105508

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016100151

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016104484

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2022106616

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021101446

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101015

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104928

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105280

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101269

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104128

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100376

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2015102013

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017100415

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103523

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102743

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102434

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104157

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103425

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018103766

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018104330

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019100512

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018104790

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2022100675

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2022100269

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021105803

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021101539

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101351

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021104604

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102645

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105398

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103371

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102382

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103986

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020107205

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105778

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105803

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100648

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020110061

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100058

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100187

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021109101

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021107374

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021103610

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105207

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101576

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106412

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103675

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021106655

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106445

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103935

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104114

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021100746

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016105883

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021102206

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105269

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017105082

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018106273

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018104963

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016100915

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106918

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102087

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105080

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105511

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105274

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105263

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021104251

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021104429

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021109119

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021104449

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100266

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101223

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105380

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021102285

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2022101030

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019102892

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104501

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019102935

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019106546

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100238

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106812

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020107108

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103544

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021106379

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101922

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020107189

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105282

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017105254

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2022105088

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021105759

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105554

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018100427

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019104124

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105347

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018100487

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105288

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016100503

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016105622

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105074

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018103003

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105170

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104608

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021102192

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021103443

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019103804

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019106574

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017105195

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105075

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104947

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100225

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104326

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101771

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2022102888

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102418

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105123

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2022100746

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020109045

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019102479

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021105362

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103501

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102392

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101392

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106033

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106721

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103796

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102068

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016104403

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019104329

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019102171

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021103828

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019100911

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103345

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101093

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106819

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020110030

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021109157

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021109130

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021109158

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021109147

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021105476

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021101895

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021101785

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021105488

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2022101784

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104746

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105880

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102188

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105657

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102761

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103290

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102153

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021103917

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106481

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103381

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016102692

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016101340

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021105785

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102603

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102059

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019102293

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018104455

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019102088

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019103287

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102333

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100339

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105672

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102405

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102502

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017103110

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017105794

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106313

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102609

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104571

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106497

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021102402

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021105050

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018103496

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105456

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018103774

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021106772

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021103852

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105239

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105463

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101215

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101442

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019104571

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019106742

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2022104607

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2022107345

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2022103872

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105354

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019104569

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019101288

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021100272

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102624

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018106832

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016101224

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018102433

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105568

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021105903

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021103699

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105248

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105248

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100235

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020110119

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020107209

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100756

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102627

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101108

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101463

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106349

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105699

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018103159

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019104641

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104736

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020190002

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105213

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018102859

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106745

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103068

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016105547

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017102835

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017110066

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017104105

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018100897

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021103709

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2015100894

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103346

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021105368

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105613

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103355

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102522

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021101115

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105715

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021104195

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104776

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103662

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020109100

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100296

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102221

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020110016

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106092

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018103150

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017105058

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021101990

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021101638

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021102166

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021100224

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021100593

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018109100

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017104994

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021101646

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018102718

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018104850

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104049

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105281

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018103729

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021110013

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021106924

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021102644

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100391

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020107152

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102111

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100746

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104113

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2022105261

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018110050

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018106388

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018103929

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018104861

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2022105703

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018102260

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016104762

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017104194

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018104976

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017110029

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018101305

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019103132

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018102810

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105493

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017105122

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100204

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100522

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104925

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105590

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021103814

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101858

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101917

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104510

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019104839

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018106510

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019104638

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106789

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100123

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100983

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018104460

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021104213

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019101979

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021104482

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019101899

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019103150

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105600

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103186

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106454

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103786

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100977

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021105813

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106513

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101078

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105925

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103352

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100106

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020107185

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019104979

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021103817

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106208

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2022106207

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2022103467

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017104767

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017105135

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019104258

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100713

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101711

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101394

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017102390

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105652

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016104987

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2022103910

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103981

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101454

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2022100987

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102830

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106456

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106460

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020107078

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020107009

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101232

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105278

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021106125

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021103170

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021101755

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021101723

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019104078

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018104250

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019104772

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016101180

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018104662

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019100596

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021101158

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021102890

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021103692

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021101188

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018110015

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016105188

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019102512

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2015100902

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017190001

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016101455

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017100024

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017101791

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103087

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100836

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104583

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102165

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018106531

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2022106665

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100178

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020107021

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105311

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016106316

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100562

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104967

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2022106619

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021106960

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021104385

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021103309

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017105317

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2014103095

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104301

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021104093

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021105376

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101842

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020107139

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102193

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2015101014

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105485

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016103103

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018110017

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021101968

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021106571

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021101945

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021106627

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100846

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101153

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021107225

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103452

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104047

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018102398

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105562

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018104827

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017106330

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105090

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2015104349

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016100418

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017101591

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020110035

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020110056

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106703

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106825

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105460

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104504

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100159

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016100758

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019103076

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018103812

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105230

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018100504

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021104118

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103377

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100348

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100722

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100682

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021106889

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019101223

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018106232

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018104699

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106824

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103067

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101773

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106124

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100517

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021100279

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021101860

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020110046

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020109109

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019100157

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021100893

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106356

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106646

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104348

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100670

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101300

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021102431

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021100803

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2022107140

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105541

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018103094

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021105493

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021105428

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019102944

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2014103040

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2012103532

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017110122

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101304

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102569

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106814

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106163

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106965

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100507

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101249

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019106713

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019103518

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018104746

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018104403

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105628

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020107029

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2013106474

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101806

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101427

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105215

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021101171

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017105597

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2014103394

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017106038

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018102574

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017101183

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017106553

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016104844

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016102075

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016102056

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2014100814

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016100598

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021103023

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100504

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106558

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104028

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106784

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105607

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104399

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020110139

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100968

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100393

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104500

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018102988

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019106702

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106566

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101964

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105584

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017104824

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105108

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019106198

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021103297

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105460

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100514

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100223

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021104719

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105641

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102548

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104505

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100575

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103836

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021104247

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021104372

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103341

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100945

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020109115

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102482

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018103558

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2014100555

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101982

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103607

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102848

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100427

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106971

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020109147

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019102406

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021106933

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016105239

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105027

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021100447

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106381

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019100489

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017104815

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105195

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021105051

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018104765

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105630

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103461

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104521

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021104802

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104465

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105247

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102155

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105064

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020107135

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017103572

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019102327

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017105054

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105067

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103563

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102619

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101150

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101155

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018103805

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017103871

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103293

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020107120

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103223

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106990

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102192

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106187

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106151

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105776

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018104957

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018104801

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102220

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019100773

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2014109137

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018102035

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018104977

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017104771

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103116

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105936

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104307

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101584

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021105302

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105532

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104405

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101758

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101776

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106575

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106707

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105293

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104335

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103213

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2013105645

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018100439

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017103170

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016103900

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100470

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100274

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021110093

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021103151

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104085

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020110027

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020110014

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106679

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020110124

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106478

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103244

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021101821

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021102393

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021107149

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103401

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106897

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104498

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106500

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101787

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103954

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100574

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021105126

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021103271

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018101579

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105205

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106216

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016106453

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018101559

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2015102403

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016102184

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017103497

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021104144

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104565

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021105684

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021105166

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021102723

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019100353

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103460

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106242

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019103006

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018102039

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021106286

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019104943

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017110144

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105069

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018101646

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100980

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106735

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100633

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102657

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105403

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102064

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021105518

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021105027

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105344

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104858

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101609

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103580

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018101616

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101981

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019103772

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018106897

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102681

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018102715

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017104689

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2015104456

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018100929

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021105947

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021103329

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017101731

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017105343

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2015103374

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2015102637

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019102930

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2015103627

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021103166

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105065

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019104930

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019106589

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019103360

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017104453

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017104724

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020107194

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106139

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021103527

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018101768

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2022103554

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017100459

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104341

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105875

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101431

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103004

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101621

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2015101281

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105108

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021100756

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017100511

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105463

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021106389

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021107368

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021107392

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018100026

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017105642

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021104149

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021102035

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021100254

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021104555

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021105906

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021110052

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019102208

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018104326

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104621

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100878

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016104819

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2014110107

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018102030

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105427

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017105332

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021102750

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021103777

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017106216

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021105248

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019100603

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017101707

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2015102735

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021101410

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021104212

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102647

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021104007

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100874

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100915

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104792

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103980

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017104989

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101843

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104630

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105151

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016103080

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021103605

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021102738

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021103926

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101923

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100870

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104387

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019103054

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101697

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105152

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105717

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106761

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102157

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100063

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105947

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106361

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016104429

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2022103513

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105402

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2015100635

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2014105589

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101345

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100486

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103906

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020109135

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104539

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2022103525

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017105048

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017103617

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105609

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018104800

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019100735

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100221

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101836

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105306

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2015104270

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105112

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017105451

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018103024

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021101743

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021103433

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016102670

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018104789

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2014103367

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017106255

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021100429

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021105725

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021103824

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021100869

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021102560

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021102684

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103494

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103872

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019102754

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100837

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102172

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103748

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106868

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101201

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100134

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105972

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105975

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100585

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101862

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104494

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103529

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2022100617

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103278

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106618

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100334

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021105514

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105004

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019100053

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2022101820

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2022102093

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101788

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105707

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101793

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104593

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017102686

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021101955

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017101184

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021106973

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105231

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019104693

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016100059

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104551

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019106382

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017101895

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017103803

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016104549

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101568

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021104489

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020110108

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021106452

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021101720

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106464

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100754

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105335

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021104569

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021101767

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101973

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100372

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105756

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105233

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019104740

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018101871

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019102316

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021102018

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021104278

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105386

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021101811

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021102429

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021106788

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018104260

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105546

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2022190001

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018102731

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021104175

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021102836

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020109050

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106810

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101593

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104655

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103097

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020107097

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104568

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101985

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106935

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100242

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106915

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103334

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101997

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021104981

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018101979

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102524

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105477

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020110150

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102183

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100913

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105806

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106543

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016104990

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2015100831

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018104114

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017101419

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105852

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016106585

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019102155

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019100049

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017105502

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019106918

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105161

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2022101116

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021101667

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021102397

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104482

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103459

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102555

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021106597

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018104696

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017104315

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100207

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105279

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105290

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021100689

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105050

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019106001

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102763

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104819

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017100915

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017101967

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019104013

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2022101018

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103422

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102245

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103357

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104795

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017104718

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019110065

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021105083

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104242

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021104369

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104253

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100234

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104020

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103041

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102694

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100327

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105597

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017103616

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017105389

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016102142

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017101528

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101739

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105941

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102916

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104698

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2015101581

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100839

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019106347

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019100492

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021100723

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021103335

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018100078

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102826

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106866

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106097

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019103225

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018106559

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105743

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102454

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018104961

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016104946

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102263

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105138

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105549

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102122

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106655

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103399

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105967

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105661

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101987

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100126

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021101024

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017104302

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019101983

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017104165

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103184

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100608

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2022102288

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018102813

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105352

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103612

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021103915

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105068

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103272

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020109013

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103485

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018102600

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105060

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017101449

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017105620

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2014102163

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2015104186

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019100808

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019103671

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100172

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021103830

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021100861

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102007

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100715

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101911

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020107145

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102983

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103587

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104547

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021102977

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021102383

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016105272

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021101832

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103791

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017105116

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017104629

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018103369

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103024

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2022106664

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019102694

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021106837

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021102978

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100971

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021103378

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021100321

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102643

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019110014

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019104577

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2014103615

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017101342

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016105875

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018101771

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018106213

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018100424

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019106437

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103914

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021107028

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100822

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104401

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016101015

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103763

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2022102704

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105401

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016105713

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016104231

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017105292

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018104365

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019100690

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021100277

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016101147

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017105576

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018102938

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021102542

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021100029

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105273

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018104324

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105938

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019104946

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106511

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106533

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100943

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106744

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021102382

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102376

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101410

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101738

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100623

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105222

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2015101660

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016102867

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016104635

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018104086

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105524

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103408

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016102102

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021106803

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105838

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101937

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105609

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021105456

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021106901

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2022105332

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103606

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103691

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100147

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021105280

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105168

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101714

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103406

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103262

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018104092

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103153

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021104779

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021106871

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019102218

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100442

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101955

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105673

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104699

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017105916

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019100575

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020109042

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103880

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105825

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104202

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021100802

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104220

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102666

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105377

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102150

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102062

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021109144

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021101570

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100279

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103152

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105210

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103379

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105252

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104771

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018104348

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105017

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021100688

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017101693

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018100650

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019101156

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100986

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104236

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106195

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106883

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018104401

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019104936

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021109116

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018106887

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021102625

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105276

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021102430

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021107343

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105208

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105473

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100546

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019100463

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103689

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018106881

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019104666

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021107185

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105693

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101626

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2022100814

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2015105078

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017102597

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018109057

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100788

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106236

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104225

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021105420

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016103046

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018103248

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103468

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105516

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100031

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102543

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103913

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021101208

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021101112

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021103262

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100304

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017105795

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101720

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021102143

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021106614

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019103838

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101791

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104554

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018100723

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100694

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020109038

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104471

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021101037

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019102537

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019106914

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106204

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105576

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105127

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019101811

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2022102496

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100866

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106312

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019101833

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019104570

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103214

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104963

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106441

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101073

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104464

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106621

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019104947

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106476

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102692

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020107023

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021102309

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019101761

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2014109151

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2015110004

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019110067

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021104502

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018106129

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017105445

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016105167

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016103787

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103707

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104557

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021105836

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103490

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2022104406

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101063

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021105520

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021106781

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019101222

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102505

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104907

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018106616

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018100963

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017105721

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101220

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102842

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105039

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105774

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100689

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100700

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020107110

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017101597

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018101329

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103846

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017102031

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017105416

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021100042

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021103731

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018103023

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021103188

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106673

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018110118

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019102502

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018102884

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018102345

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018104934

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102782

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106362

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105316

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020107013

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021103273

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021104704

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105140

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2022105957

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100518

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020110018

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103476

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103631

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106544

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100155

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021100437

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021101709

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103216

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2014105506

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017106451

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021105359

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021107367

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018106464

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021104718

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2015101170

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105353

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020107114

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019103234

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020110070

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020110111

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020110063

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102696

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018104979

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101104

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106972

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104588

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104127

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016101207

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017106027

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102661

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021100926

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021104864

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101076

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106167

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017105469

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017105498

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021103787

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105504

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020107179

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020110096

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106323

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017105192

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016104496

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017102196

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016109066

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103317

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105321

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021101047

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2015105691

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016100182

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018103418

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105384

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018104955

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017104973

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016103294

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017105495

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017105225

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018110099

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017105458

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019102084

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105955

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103109

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105989

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105528

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021105163

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2022102282

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103573

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100697

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105122

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105535

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101736

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103177

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2022100787

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018103300

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019101914

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2022106260

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019104514

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104784

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102869

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100831

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103743

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019102232

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017103831

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100501

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101977

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021103848

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101414

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101071

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101053

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102875

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100036

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105138

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019104616

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018104951

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102707

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106235

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020109150

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100918

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021102045

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021102183

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102352

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100932

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021101460

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102581

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018102757

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104166

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103518

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101033

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018104320

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018102985

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105169

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105326

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101325

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103506

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105447

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021105404

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106929

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103932

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102677

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019100954

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019102817

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018103861

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021100738

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018103139

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103326

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020107031

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2022107072

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2014104240

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103722

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103611

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017106395

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102746

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021105979

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105970

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105674

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100414

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021105029

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016104500

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018100017

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103752

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105497

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017104776

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103514

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101080

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100025

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102846

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020110115

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100764

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104841

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106710

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016104480

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018110088

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019103949

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106237

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100920

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104186

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102233

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016103099

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019104871

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101980

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102217

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020107219

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105589

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020107039

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106892

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104173

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017100540

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2022102265

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104899

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020107052

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104298

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019110052

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019103094

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021109100

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017102175

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104953

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100622

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100435

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017105297

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021105633

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017105276

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104139

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017105144

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017102513

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017101334

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017102191

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106318

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020109149

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103347

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019102306

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021104687

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021106491

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018103149

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102905

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102311

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100857

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017100969

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018100282

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019103841

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019102524

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106881

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106397

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105355

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106029

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017190002

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017106711

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021104042

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021104657

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2022106812

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104828

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017104884

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019106256

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102909

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104681

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017100519

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104273

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019106083

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101333

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106656

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102777

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018100903

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019106062

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016102156

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021100550

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103970

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101767

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105521

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019103954

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105414

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021105909

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101628

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103415

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103137

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103032

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018104368

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019103583

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105978

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105431

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017103291

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2014100576

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2022102640

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105616

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100645

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103233

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102442

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102989

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016100527

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2015102211

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2015103845

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017101363

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019100547

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105082

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019104042

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101595

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105052

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106666

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021104813

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101824

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101706

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106008

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021102655

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021100750

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020107085

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019106765

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102585

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104277

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019103512

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2022104262

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103800

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105242

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103974

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105297

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021105026

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104549

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103839

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018104267

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103011

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021101857

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018104253

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017102833

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105561

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016104659

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020109158

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021105134

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021100194

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021104701

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021102048

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2022100770

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018102794

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018100710

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105479

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021105343

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102573

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018101782

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019103143

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019109123

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019110116

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020107123

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106279

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102839

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104095

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104889

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017105572

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106030

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101318

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103210

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105548

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104507

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103781

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017101560

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102052

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100653

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104193

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017103237

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017105050

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017101816

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103072

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102691

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2013109027

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2015102215

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021101829

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102669

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019100624

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018103087

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102922

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101857

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102662

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103627

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103946

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106360

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102626

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106769

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102908

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2013100975

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016104137

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018104616

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018101500

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105098

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100483

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2022100210

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103704

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017105553

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2015102038

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101329

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101022

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104430

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105580

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104081

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101518

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101636

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105116

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018101618

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018102167

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2015104417

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017104964

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2022106458

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106802

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100718

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021101916

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021106137

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104995

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019100920

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101829

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101007

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018104769

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105670

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018104111

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105007

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2015106353

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017105649

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016102269

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017104903

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103725

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103647

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105623

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018104745

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105767

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105433

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104677

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103374

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104361

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102136

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018103735

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104219

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103335

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106622

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021106280

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106477

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018103115

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106165

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2015100887

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016110013

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106383

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100737

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018106407

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102301

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102939

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104438

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016100097

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019100388

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101848

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016105872

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018103001

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101693

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101646

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100027

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103170

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104647

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101348

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100371

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2022105681

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021104734

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104742

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106159

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105132

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018100545

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106524

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103353

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100009

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104956

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105686

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102822

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102255

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105107

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016110070

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018103931

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018103340

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102047

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019110043

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103797

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100396

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021101027

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102650

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104493

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100627

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106786

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105646

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2022106253

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019104487

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017105472

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104177

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105198

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017103143

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100612

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100385

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104339

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019106950

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105459

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106853

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102824

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106991

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105846

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101882

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102533

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105209

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103983

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103734

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019100579

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020110008

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101754

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106924

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105555

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102699

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018102386

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016106157

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101266

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105935

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103658

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105323

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2014100050

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102177

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2022106967

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2022106202

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105043

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106870

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021105482

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102100

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019106880

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2014104432

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100421

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021106981

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021106140

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021106532

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105051

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018102939

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017105072

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020190003

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020190004

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019101625

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2013103792

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018101891

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2022103224

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2022102357

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105371

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100601

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104801

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104483

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021102261

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100409

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100712

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018106002

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104050

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021106524

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104938

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019106579

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021104724

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106652

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021104357

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021104223

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017103382

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019106481

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106864

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021107117

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103296

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2022106636

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2022103772

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016104563

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021102152

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018106582

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2013101259

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017103482

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018106502

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018102000

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017105383

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018103408

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2022101861

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2022100570

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102917

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017100968

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105368

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021102314

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019102814

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021105309

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021106687

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017100381

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105432

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102863

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101809

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103618

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106594

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2015105026

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016105210

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021105586

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105285

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101006

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102017

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021101853

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101418

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105175

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017102141

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105629

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016104444

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103252

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105629

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018110120

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017105660

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021100383

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101645

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104338

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019102663

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104876

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104421

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100107

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018104716

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105636

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103683

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021107074

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105375

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100467

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017103973

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016105024

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105337

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102889

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017104986

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017106220

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106448

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105192

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019103320

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021104705

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017104675

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2014103358

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2012104504

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2012104463

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2014106228

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105731

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017100174

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018110065

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021103315

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017104921

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017106645

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019105367

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100750

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103637

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103571

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103723

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105937

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104268

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103176

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021101439

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2013106025

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100739

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104906

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017110151

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103687

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103151

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020110037

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016103768

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021105136

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104839

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101947

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101729

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105146

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101994

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016102571

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2015102321

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020106942

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017105011

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018102535

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100751

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018100729

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021100156

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018102231

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103773

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105370

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020107010

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018101051

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018102296

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019106660

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018105443

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100240

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102659

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2021101583

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018103804

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2014102698

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2019104096

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101834

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104891

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105462

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105882

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017105409

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2015110086

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017105509

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017106414

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018101486

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017105186

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103031

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017101010

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104492

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020101934

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020110129

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020103916

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018106082

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100164

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020105725

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020107131

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2018103280

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104011

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2016105702

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020104835

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2017101909

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102850

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020100346

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

[SKIP NO UPDATE] 2020102558

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:157: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

In [15]:
#欠損値チェック
horse_results.index.unique()

#重複チェック

RangeIndex(start=0, stop=350325, step=1)

##  レース情報の取得

In [7]:
import create_rawdf

#html_paths_raceが失われた場合はファイルから読み込む
if "html_paths_race" not in locals():
    html_paths_race=list(scraping.HTML_RACE_DIR.glob("*.bin"))

race_info=create_rawdf.create_race_info(html_paths_race)

  0%|          | 0/10365 [00:00<?, ?it/s]

KeyboardInterrupt:

In [30]:
race_info

,race_id,title,info1,info2
0,202406010111,第73回日刊スポ賞中山金杯(GIII),"[芝右2000m, 天候:晴, 芝:良, 発走:15:45, 過去の日刊スポ賞中山金杯]","[2024年1月6日, 1回中山1日目, 4歳以上オープン, 国際, 特指, ハンデ]"
1,202309020109,君子蘭賞(1勝),"[芝右外1800m, 天候:曇, 芝:良, 発走:14:25, 過去の君子蘭賞]","[2023年3月25日, 2回阪神1日目, 3歳1勝クラス, 牝, 特指, 馬齢]"
2,202303020408,3歳以上1勝クラス,"[芝右1800m, 天候:曇, 芝:良, 発走:14:05]","[2023年7月9日, 2回福島4日目, 3歳以上1勝クラス, 混, 特指, 定量]"
3,202307020402,3歳未勝利,"[ダ左1900m, 天候:晴, ダート:重, 発走:10:20]","[2023年3月19日, 2回中京4日目, 3歳未勝利, 指, 馬齢]"
4,202410020205,3歳未勝利,"[芝右2000m, 天候:晴, 芝:良, 発走:12:10]","[2024年2月11日, 2回小倉2日目, 3歳未勝利, 指, 馬齢]"
...,...,...,...,...
6905,202407040401,2歳未勝利,"[ダ左1200m, 天候:晴, ダート:良, 発走:09:55]","[2024年12月8日, 4回中京4日目, 2歳未勝利, 指, 馬齢]"
6906,202403020412,彦星賞(2勝),"[ダ右1150m, 天候:晴, ダート:良, 発走:16:30, 過去の彦星賞]","[2024年7月7日, 2回福島4日目, 3歳以上2勝クラス, 混, 指, 定量]"
6907,202403020406,2歳新馬,"[芝右1200m, 天候:晴, 芝:良, 発走:13:05]","[2024年7月7日, 2回福島4日目, 2歳新馬, 指, 馬齢]"
6908,202408060403,2歳未勝利,"[芝右1600m, 天候:晴, 芝:良, 発走:11:00]","[2024年11月10日, 6回京都4日目, 2歳未勝利, 混, 指, 馬齢]"
6909,202408060704,障害3歳以上未勝利,"[障芝ダート2910m, 天候:曇, 芝:良, ダート:良, 発走:11:35]","[2024年11月23日, 6回京都7日目, 障害3歳以上未勝利, 混, 定量]"

##  予想

In [8]:
import create_prediction_population
import scraping
%load_ext autoreload

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [9]:
autoreload

In [ ]:
#html_paths_predict=scraping.scrape_html_predict_race

In [11]:
prediction_population=create_prediction_population.create(kaisai_date="20260118")

scraping race_id_list...

  0%|          | 0/1 [00:00<?, ?it/s]

scraping horse_id_list...

  0%|          | 0/24 [00:00<?, ?it/s]

In [12]:
prediction_population

         date       race_id    horse_id
0  2026-01-18  202606010701  2023106600
1  2026-01-18  202606010701  2023104793
2  2026-01-18  202606010701  2023102383
3  2026-01-18  202606010701  2023105553
4  2026-01-18  202606010701  2023106991
..        ...           ...         ...
6  2026-01-18  202608010712  2022105407
7  2026-01-18  202608010712  2022105123
8  2026-01-18  202608010712  2022105715
9  2026-01-18  202608010712  2022103736
10 2026-01-18  202608010712  2022104738

[351 rows x 3 columns]

In [13]:
html_paths_horse_predict=scraping.scrape_html_horse(
    horse_id_list=prediction_population["horse_id"].unique(),
    skip=False)

  0%|          | 0/351 [00:00<?, ?it/s]

In [14]:
import create_rawdf

horse_results_prediction=create_rawdf.create_horse_results(
    html_path_list=html_paths_horse_predict,
    save_filename="horse_results_prediction.csv"
)

  0%|          | 0/351 [00:00<?, ?it/s]

/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:181: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:181: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:181: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:181: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:181: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:181: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:181: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:181: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:181: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:181: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:181: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:181: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:181: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:181: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:181: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:181: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:181: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:181: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)
/home/jawa/horse_ai/horse_race_prediction/common/src/create_rawdf.py:181: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html_fragment)

KeyboardInterrupt: